import type { Lens } from '@/types/reality'

export const LENSES: Lens[] = [
  {
    id: 'logic',
    name: 'Logic',
    description: 'Strips emotion away and evaluates only verifiable facts and valid inferences.',
    coreQuestion: 'What do the facts actually say, independent of how I feel about them?',
    blindSpot: 'Ignores emotional and social context that is often relevant to human decisions.',
    power: 'Cuts through distortion and reveals what is actually true versus what is assumed.',
    examples: [
      'She took 6 hours to reply — is there actual evidence she is losing interest?',
      'I made a mistake at work — does that fact alone mean I will be fired?',
      'He seemed annoyed — do I have direct evidence of that, or is it inference?',
    ],
  },
  {
    id: 'religion',
    name: 'Religion / Meaning',
    description: 'Looks for deeper purpose, growth, or design in difficult events.',
    coreQuestion: 'What deeper purpose could this difficulty serve in my development?',
    blindSpot: 'Can rationalise avoidance of real-world action under the guise of "trust the process".',
    power: 'Converts adversity into narrative — suffering becomes meaningful, not random.',
    examples: [
      'This rejection could be redirecting me toward something better aligned.',
      'This failure may be developing resilience I could not build any other way.',
      'The obstacle in front of me may be the curriculum for this chapter.',
    ],
  },
  {
    id: 'mating',
    name: 'Mating / Attraction',
    description: 'Views situations through the lens of attraction dynamics, confidence, and sexual strategy.',
    coreQuestion: 'How does my response to this situation affect how I am perceived by others?',
    blindSpot: 'Can reduce complex human relationships to pure game theory, missing genuine connection.',
    power: 'Reveals how emotional reactions undermine attractiveness and social positioning.',
    examples: [
      'Anxiety-texting after no reply signals scarcity and reduces perceived value.',
      'Staying calm in conflict is itself a display of emotional security.',
      'Chasing approval inverts the polarity that creates attraction.',
    ],
  },
  {
    id: 'statistics',
    name: 'Statistics',
    description: 'Evaluates whether one event is enough data to draw a conclusion.',
    coreQuestion: 'Is this one data point, or an actual pattern with a large enough sample?',
    blindSpot: 'Can dismiss real signals by over-demanding statistical proof in human contexts.',
    power: 'Prevents premature conclusions drawn from single events or emotional salience.',
    examples: [
      'One bad date is not evidence you are undateable.',
      'One good meeting does not mean the deal is closed.',
      'One anxious day does not define your baseline mood.',
    ],
  },
  {
    id: 'science',
    name: 'Science',
    description: 'Asks what mechanism produced the outcome — what cause generated this effect.',
    coreQuestion: 'What is the mechanism here? What specific cause produced this effect?',
    blindSpot: 'Misses that human systems are far messier than controlled experiments.',
    power: 'Moves attention from outcomes (which you cannot control) to inputs (which you can).',
    examples: [
      'Why did the conversation go badly? What specific input triggered the shift?',
      'What physiological state am I in and how is it shaping my perception right now?',
      'What is the repeatable process change that would produce a different outcome?',
    ],
  },
  {
    id: 'persuasion',
    name: 'Persuasion',
    description: 'Asks who benefits from you holding the belief you currently hold.',
    coreQuestion: 'Who installed this frame in my head, and does it serve me or them?',
    blindSpot: 'Can breed excessive cynicism — not every belief is an installed manipulation.',
    power: 'Reveals that many of your most painful beliefs were put there by others for their benefit.',
    examples: [
      'Social media is designed to make you feel inadequate so you keep scrolling.',
      'The frame that you should feel ashamed of this — who benefits from you feeling that way?',
      'Advertising created the insecurity this product now claims to solve.',
    ],
  },
  {
    id: 'economics',
    name: 'Economics',
    description: 'Maps the real incentives driving behavior rather than stated intentions.',
    coreQuestion: "What are the actual incentives driving this person's behavior?",
    blindSpot: 'Reduces human motivation to pure self-interest, missing genuine altruism.',
    power: 'Predicts behavior far more accurately than stated intentions or moral expectations.',
    examples: [
      'Why did they behave that way? What did they stand to gain or lose?',
      'What is the cost-benefit calculation driving this decision?',
      "The incentive structure explains the behavior — not the person's character.",
    ],
  },
  {
    id: 'simulation',
    name: 'Simulation Theory',
    description: 'Treats reality as a simulation and asks what the optimal player would do.',
    coreQuestion: 'If this is one scenario in a simulation, what would the optimal player do right now?',
    blindSpot: 'Can be used to avoid genuine emotional engagement by over-intellectualising.',
    power: 'Dissolves the weight of events by reframing them as gameplay rather than permanent reality.',
    examples: [
      'The optimal player in this scenario does not let one bad event derail the entire run.',
      'What move maximises long-term score here, regardless of how it feels?',
      'A character in a game does not stop playing because of one difficult level.',
    ],
  },
  {
    id: 'winners-losers',
    name: 'Winners vs Losers',
    description: 'Asks what the winner of this situation does versus what the loser does.',
    coreQuestion: 'What does the winner of this situation do next?',
    blindSpot: 'Binary framing can miss nuance and create unnecessary competition where none exists.',
    power: 'Cuts through self-pity and indecision by making the right move obvious through contrast.',
    examples: [
      'The loser replays the failure. The winner extracts the lesson and moves.',
      'The loser chases validation. The winner continues building.',
      'What would someone who handles this well do in the next ten minutes?',
    ],
  },
  {
    id: 'predator-prey',
    name: 'Predator vs Prey',
    description: 'Asks whether you are responding from a position of power or reacting from fear.',
    coreQuestion: 'Am I hunting strategically, or reacting like prey to a perceived threat?',
    blindSpot: 'Can promote aggression or dominance framing in situations that call for vulnerability.',
    power: 'Reveals when you are being reactive and giving others control over your state.',
    examples: [
      'Prey sends a defensive message immediately. Predators choose their moment.',
      'Prey interprets silence as a threat. Predators treat it as neutral.',
      'Am I acting from abundance and choice, or from fear of loss?',
    ],
  },
  {
    id: 'strategy',
    name: 'Strategy',
    description: 'Evaluates the long game — what move serves your position best over time.',
    coreQuestion: 'What is the long game here, and what move serves me best six months from now?',
    blindSpot: 'Can delay necessary immediate action in the name of long-term positioning.',
    power: 'Converts emotional impulse into calculated positioning — the short term stops running the show.',
    examples: [
      'Winning this argument today may lose the relationship long-term.',
      'The impulsive response feels satisfying but costs leverage.',
      'What position do I want to be in six months, and does this move get me there?',
    ],
  },
  {
    id: 'abundance',
    name: 'Abundance Mindset',
    description: 'Views this situation from a position of plenty rather than scarcity.',
    coreQuestion: 'What does this situation look like from a position of genuine abundance?',
    blindSpot: 'Can dismiss real scarcity that requires urgent action rather than mindset shifts.',
    power: 'Eliminates the desperation that causes the worst decisions and outcomes.',
    examples: [
      'There are other people. There are other opportunities. This one closing is not the end.',
      "One person's rejection does not define what is available to you.",
      'From abundance, you can afford to wait, to choose, to walk away.',
    ],
  },
  {
    id: 'moist-robot',
    name: 'Moist Robot',
    description: 'Views the self as a biological machine — inputs produce outputs, feelings are system states.',
    coreQuestion: 'What input produced this output in my system, and which variable can I change?',
    blindSpot: 'Taken too far, it can dismiss the moral significance of emotion and human experience.',
    power: 'Removes the drama from emotional states and makes them tractable engineering problems.',
    examples: [
      'I am feeling anxious because my sleep was poor and my caffeine is high — not because the situation is dangerous.',
      'This emotion is an output. What is the input I can change?',
      'I am not the feeling. I am the system generating the feeling.',
    ],
  },
  {
    id: 'victim-oppressor',
    name: 'Victim vs Oppressor',
    description: 'Asks whether you are taking ownership or assigning blame as a substitute for action.',
    coreQuestion: 'Am I taking full ownership of my response, or blaming as a substitute for action?',
    blindSpot: 'Can pressure people to accept responsibility for situations that are genuinely unfair.',
    power: 'Restores agency — even in unfair situations, you always control your response.',
    examples: [
      'The situation may be unfair AND there is still something I can do.',
      'Assigning blame is satisfying but does not change my position.',
      'What is the one thing fully within my control right now?',
    ],
  },
  {
    id: 'mind-reading',
    name: 'Mind Reading',
    description: 'Identifies when you are treating invented thoughts about others as confirmed fact.',
    coreQuestion: 'Am I reading minds, or do I have actual evidence for what I think they think?',
    blindSpot: 'Sometimes intuition about others is accurate — this lens can dismiss real social signals.',
    power: 'Stops you from acting on fictional narratives you constructed about other people\'s thoughts.',
    examples: [
      'You decided they are judging you — but do you actually know that?',
      'You know what they were thinking when they went quiet — but do you?',
      'The story you have about their reaction may be entirely invented.',
    ],
  },
]

export function getLens(id: string): Lens | undefined {
  return LENSES.find(l => l.id === id)
}
