// lib/foods.ts
// Complete food library with macros, portions, and phase recommendations

import type { Phase } from "@/lib/cycle";
export type { Phase };
export type MealType = "breakfast" | "lunch" | "dinner" | "snack";

export interface FoodItem {
  id: string;
  name: string;
  emoji: string;
  phase: Phase;
  mealType: MealType;
  reason: string;         // why it's good for this phase
  portion: string;        // e.g. "200g", "1 cup"
  calories: number;
  protein: number;        // grams
  carbs: number;          // grams
  fats: number;           // grams
  fiber?: number;         // grams
  keyNutrient: string;    // e.g. "Iron", "Omega-3", "Magnesium"
}

export const FOOD_LIBRARY: FoodItem[] = [

  // ─────────────────────────────────────────────────────────────
  // MENSTRUAL PHASE — Iron, Omega-3s, Magnesium, Anti-inflammatory
  // ─────────────────────────────────────────────────────────────

  {
    id: "men-01",
    name: "Salmon + Avocado Rice Bowl",
    emoji: "🥑", phase: "menstrual", mealType: "lunch",
    reason: "Omega-3s reduce inflammation and cramping",
    portion: "150g salmon + 100g rice + ½ avocado",
    calories: 520, protein: 38, carbs: 42, fats: 18, fiber: 5,
    keyNutrient: "Omega-3",
  },
  {
    id: "men-02",
    name: "Dark Chocolate + Almonds",
    emoji: "🍫", phase: "menstrual", mealType: "snack",
    reason: "Magnesium relieves cramps and boosts mood",
    portion: "30g dark chocolate (70%+) + 20g almonds",
    calories: 215, protein: 4, carbs: 18, fats: 14, fiber: 3,
    keyNutrient: "Magnesium",
  },
  {
    id: "men-03",
    name: "Lentil & Spinach Soup",
    emoji: "🍲", phase: "menstrual", mealType: "lunch",
    reason: "Iron + folate replenish blood loss",
    portion: "300ml soup (1.5 cups)",
    calories: 280, protein: 16, carbs: 38, fats: 4, fiber: 12,
    keyNutrient: "Iron",
  },
  {
    id: "men-04",
    name: "Warm Ginger Tea + Medjool Dates",
    emoji: "🫖", phase: "menstrual", mealType: "snack",
    reason: "Ginger eases cramps, dates provide natural iron",
    portion: "250ml tea + 3 dates",
    calories: 165, protein: 1, carbs: 44, fats: 0, fiber: 4,
    keyNutrient: "Iron",
  },
  {
    id: "men-05",
    name: "Beef + Sweet Potato Mash",
    emoji: "🥩", phase: "menstrual", mealType: "dinner",
    reason: "Heme iron from beef + vitamin C from sweet potato for absorption",
    portion: "120g beef mince + 200g sweet potato",
    calories: 480, protein: 32, carbs: 45, fats: 14, fiber: 6,
    keyNutrient: "Iron",
  },
  {
    id: "men-06",
    name: "Scrambled Eggs + Whole Grain Toast",
    emoji: "🍳", phase: "menstrual", mealType: "breakfast",
    reason: "B12 and protein to maintain energy during fatigue",
    portion: "3 eggs + 2 slices toast",
    calories: 380, protein: 22, carbs: 38, fats: 14, fiber: 4,
    keyNutrient: "B12",
  },
  {
    id: "men-07",
    name: "Chamomile + Turmeric Latte",
    emoji: "☕", phase: "menstrual", mealType: "snack",
    reason: "Anti-inflammatory, reduces bloating and anxiety",
    portion: "250ml with oat milk",
    calories: 85, protein: 2, carbs: 14, fats: 2, fiber: 0,
    keyNutrient: "Anti-inflammatory",
  },
  {
    id: "men-08",
    name: "Pumpkin Seed Yogurt Bowl",
    emoji: "🌱", phase: "menstrual", mealType: "breakfast",
    reason: "Pumpkin seeds are the richest plant source of zinc + magnesium",
    portion: "150g Greek yogurt + 30g pumpkin seeds + berries",
    calories: 310, protein: 18, carbs: 22, fats: 14, fiber: 3,
    keyNutrient: "Zinc + Magnesium",
  },
  {
    id: "men-09",
    name: "Sardines on Rye Crackers",
    emoji: "🐟", phase: "menstrual", mealType: "snack",
    reason: "Sardines packed with iron, omega-3, and calcium",
    portion: "1 can sardines (90g) + 4 rye crackers",
    calories: 290, protein: 22, carbs: 24, fats: 10, fiber: 3,
    keyNutrient: "Omega-3 + Iron",
  },
  {
    id: "men-10",
    name: "Banana + Almond Butter",
    emoji: "🍌", phase: "menstrual", mealType: "snack",
    reason: "Potassium reduces water retention, magnesium eases cramps",
    portion: "1 medium banana + 2 tbsp almond butter",
    calories: 285, protein: 7, carbs: 36, fats: 14, fiber: 4,
    keyNutrient: "Potassium + Magnesium",
  },
  {
    id: "men-11",
    name: "Bone Broth + Veggies",
    emoji: "🍵", phase: "menstrual", mealType: "dinner",
    reason: "Collagen and minerals support gut and reduce inflammation",
    portion: "300ml broth + mixed vegetables",
    calories: 180, protein: 12, carbs: 18, fats: 4, fiber: 5,
    keyNutrient: "Collagen + Minerals",
  },
  {
    id: "men-12",
    name: "Chia Pudding with Berries",
    emoji: "🍓", phase: "menstrual", mealType: "breakfast",
    reason: "Omega-3 ALA and fiber, gentle on digestion",
    portion: "40g chia seeds + 200ml oat milk + berries",
    calories: 340, protein: 10, carbs: 38, fats: 16, fiber: 14,
    keyNutrient: "Omega-3 ALA",
  },

  // ─────────────────────────────────────────────────────────────
  // FOLLICULAR PHASE — Complex carbs, Lean protein, B vitamins
  // ─────────────────────────────────────────────────────────────

  {
    id: "fol-01",
    name: "Oat Bowl + Berries + Boiled Eggs",
    emoji: "🥣", phase: "follicular", mealType: "breakfast",
    reason: "Complex carbs + protein fuels rising energy and muscle growth",
    portion: "80g oats + 100g berries + 2 eggs",
    calories: 480, protein: 22, carbs: 68, fats: 10, fiber: 8,
    keyNutrient: "Complex Carbs",
  },
  {
    id: "fol-02",
    name: "Chicken Breast + Quinoa Salad",
    emoji: "🥗", phase: "follicular", mealType: "lunch",
    reason: "Complete amino acids maximise muscle protein synthesis",
    portion: "150g chicken + 100g quinoa + greens",
    calories: 490, protein: 46, carbs: 42, fats: 8, fiber: 6,
    keyNutrient: "Complete Protein",
  },
  {
    id: "fol-03",
    name: "Greek Yogurt + Granola + Honey",
    emoji: "🫙", phase: "follicular", mealType: "breakfast",
    reason: "Probiotic + carbs replenish glycogen post-training",
    portion: "200g yogurt + 40g granola + 1 tsp honey",
    calories: 420, protein: 20, carbs: 58, fats: 10, fiber: 3,
    keyNutrient: "Probiotics",
  },
  {
    id: "fol-04",
    name: "Rice Cakes + Peanut Butter + Banana",
    emoji: "🍞", phase: "follicular", mealType: "snack",
    reason: "Fast carbs + protein — ideal pre-workout snack",
    portion: "3 rice cakes + 2 tbsp PB + ½ banana",
    calories: 320, protein: 9, carbs: 44, fats: 11, fiber: 3,
    keyNutrient: "Quick Carbs",
  },
  {
    id: "fol-05",
    name: "Tuna + Brown Rice + Broccoli",
    emoji: "🍱", phase: "follicular", mealType: "lunch",
    reason: "Lean protein + complex carbs + cruciferous veg support estrogen balance",
    portion: "130g tuna + 120g brown rice + 100g broccoli",
    calories: 450, protein: 40, carbs: 52, fats: 5, fiber: 7,
    keyNutrient: "Lean Protein",
  },
  {
    id: "fol-06",
    name: "Protein Smoothie Bowl",
    emoji: "🫐", phase: "follicular", mealType: "breakfast",
    reason: "High protein and antioxidants support muscle repair",
    portion: "1 scoop protein + 150g frozen berries + banana",
    calories: 380, protein: 28, carbs: 52, fats: 4, fiber: 7,
    keyNutrient: "Protein + Antioxidants",
  },
  {
    id: "fol-07",
    name: "Turkey + Whole Grain Wrap",
    emoji: "🌮", phase: "follicular", mealType: "lunch",
    reason: "B vitamins in turkey support energy metabolism",
    portion: "1 wrap + 100g turkey + veggies",
    calories: 420, protein: 32, carbs: 44, fats: 10, fiber: 5,
    keyNutrient: "B Vitamins",
  },
  {
    id: "fol-08",
    name: "Cottage Cheese + Pineapple",
    emoji: "🍍", phase: "follicular", mealType: "snack",
    reason: "Casein protein + bromelain enzyme aids recovery",
    portion: "200g cottage cheese + 100g pineapple",
    calories: 240, protein: 24, carbs: 28, fats: 2, fiber: 2,
    keyNutrient: "Casein Protein",
  },
  {
    id: "fol-09",
    name: "Edamame + Brown Rice Bowl",
    emoji: "🌿", phase: "follicular", mealType: "dinner",
    reason: "Plant-based complete protein + phytoestrogens support hormone balance",
    portion: "150g edamame + 120g brown rice + tamari",
    calories: 430, protein: 22, carbs: 62, fats: 8, fiber: 10,
    keyNutrient: "Phytoestrogens",
  },
  {
    id: "fol-10",
    name: "Overnight Oats + Seeds",
    emoji: "🌙", phase: "follicular", mealType: "breakfast",
    reason: "Slow-release carbs sustain energy through morning training",
    portion: "80g oats + 200ml milk + 20g mixed seeds",
    calories: 460, protein: 18, carbs: 64, fats: 14, fiber: 9,
    keyNutrient: "Slow-Release Carbs",
  },
  {
    id: "fol-11",
    name: "Salmon Poke Bowl",
    emoji: "🍣", phase: "follicular", mealType: "dinner",
    reason: "Omega-3 + complex carbs rebuild muscle after strength training",
    portion: "150g salmon + 120g sushi rice + cucumber + edamame",
    calories: 540, protein: 38, carbs: 54, fats: 16, fiber: 5,
    keyNutrient: "Omega-3 + Protein",
  },
  {
    id: "fol-12",
    name: "Apple + String Cheese",
    emoji: "🍎", phase: "follicular", mealType: "snack",
    reason: "Simple snack — natural sugar + calcium + protein",
    portion: "1 apple + 30g string cheese",
    calories: 170, protein: 7, carbs: 26, fats: 5, fiber: 4,
    keyNutrient: "Calcium",
  },

  // ─────────────────────────────────────────────────────────────
  // OVULATION PHASE — High protein, High carbs, Peak performance
  // ─────────────────────────────────────────────────────────────

  {
    id: "ovu-01",
    name: "Ribeye Steak + Sweet Potato + Greens",
    emoji: "🥩", phase: "ovulation", mealType: "dinner",
    reason: "Peak anabolic window — high protein + carbs for maximum gains",
    portion: "180g steak + 200g sweet potato + salad",
    calories: 640, protein: 48, carbs: 50, fats: 22, fiber: 8,
    keyNutrient: "Heme Iron + Zinc",
  },
  {
    id: "ovu-02",
    name: "Banana + Whey Protein Shake",
    emoji: "🍌", phase: "ovulation", mealType: "snack",
    reason: "Fast carbs + protein — perfect pre/post workout fuel",
    portion: "1 banana + 1 scoop whey + 250ml milk",
    calories: 380, protein: 32, carbs: 50, fats: 4, fiber: 3,
    keyNutrient: "Fast Protein",
  },
  {
    id: "ovu-03",
    name: "Egg White Omelette + Whole Grain Toast",
    emoji: "🍳", phase: "ovulation", mealType: "breakfast",
    reason: "High protein, low fat — maximises muscle synthesis at peak",
    portion: "5 egg whites + 2 whole eggs + 2 slices toast",
    calories: 420, protein: 36, carbs: 38, fats: 8, fiber: 4,
    keyNutrient: "High Protein",
  },
  {
    id: "ovu-04",
    name: "Chicken Rice Bowl with Avocado",
    emoji: "🍚", phase: "ovulation", mealType: "lunch",
    reason: "Carb-loading + protein for sustained high-intensity performance",
    portion: "180g chicken + 150g jasmine rice + ½ avocado",
    calories: 620, protein: 50, carbs: 58, fats: 16, fiber: 5,
    keyNutrient: "Performance Fuel",
  },
  {
    id: "ovu-05",
    name: "Tuna Pasta with Olive Oil",
    emoji: "🍝", phase: "ovulation", mealType: "lunch",
    reason: "High carb + protein for peak energy output",
    portion: "100g pasta (dry) + 130g tuna + 1 tbsp olive oil",
    calories: 580, protein: 42, carbs: 72, fats: 10, fiber: 4,
    keyNutrient: "Carb + Protein",
  },
  {
    id: "ovu-06",
    name: "Greek Yogurt + Protein Granola",
    emoji: "💪", phase: "ovulation", mealType: "breakfast",
    reason: "Morning protein hit to maximise anabolic response",
    portion: "200g yogurt + 50g protein granola",
    calories: 440, protein: 30, carbs: 50, fats: 10, fiber: 4,
    keyNutrient: "Morning Protein",
  },
  {
    id: "ovu-07",
    name: "Smoked Salmon Bagel",
    emoji: "🥯", phase: "ovulation", mealType: "breakfast",
    reason: "Omega-3 + carbs fuel peak performance",
    portion: "1 bagel + 100g smoked salmon + cream cheese",
    calories: 480, protein: 28, carbs: 56, fats: 14, fiber: 3,
    keyNutrient: "Omega-3 + Carbs",
  },
  {
    id: "ovu-08",
    name: "Rice Cakes + Turkey + Tomato",
    emoji: "🍅", phase: "ovulation", mealType: "snack",
    reason: "Lean protein + fast carbs — ideal between training sessions",
    portion: "4 rice cakes + 80g turkey + tomato",
    calories: 260, protein: 22, carbs: 32, fats: 3, fiber: 2,
    keyNutrient: "Lean Protein",
  },
  {
    id: "ovu-09",
    name: "Beef Stir Fry with Noodles",
    emoji: "🥢", phase: "ovulation", mealType: "dinner",
    reason: "Zinc from beef boosts testosterone slightly during ovulation",
    portion: "150g beef + 100g noodles + vegetables",
    calories: 560, protein: 38, carbs: 60, fats: 14, fiber: 6,
    keyNutrient: "Zinc",
  },
  {
    id: "ovu-10",
    name: "Protein Pancakes + Maple Syrup",
    emoji: "🥞", phase: "ovulation", mealType: "breakfast",
    reason: "High protein breakfast with carbs for sustained morning energy",
    portion: "3 pancakes (1 scoop protein + 2 eggs + oats) + syrup",
    calories: 480, protein: 34, carbs: 54, fats: 10, fiber: 4,
    keyNutrient: "Protein + Carbs",
  },
  {
    id: "ovu-11",
    name: "Medjool Dates + Walnuts",
    emoji: "🌰", phase: "ovulation", mealType: "snack",
    reason: "Fast energy + omega-3 from walnuts for brain and performance",
    portion: "4 dates + 30g walnuts",
    calories: 310, protein: 5, carbs: 48, fats: 14, fiber: 5,
    keyNutrient: "Fast Energy + Omega-3",
  },
  {
    id: "ovu-12",
    name: "Shrimp Fried Rice",
    emoji: "🍤", phase: "ovulation", mealType: "dinner",
    reason: "Iodine from shrimp supports thyroid and energy at peak phase",
    portion: "150g shrimp + 150g rice + egg + veggies",
    calories: 520, protein: 36, carbs: 62, fats: 10, fiber: 4,
    keyNutrient: "Iodine + Protein",
  },

  // ─────────────────────────────────────────────────────────────
  // LUTEAL PHASE — Healthy fats, Stable carbs, Magnesium, Anti-craving
  // ─────────────────────────────────────────────────────────────

  {
    id: "lut-01",
    name: "Avocado Toast + Poached Eggs",
    emoji: "🥑", phase: "luteal", mealType: "breakfast",
    reason: "Healthy fats stabilise blood sugar and prevent energy crashes",
    portion: "2 slices sourdough + 1 avocado + 2 eggs",
    calories: 520, protein: 20, carbs: 44, fats: 28, fiber: 10,
    keyNutrient: "Healthy Fats",
  },
  {
    id: "lut-02",
    name: "Mixed Nut Mix + Dark Chocolate",
    emoji: "🫘", phase: "luteal", mealType: "snack",
    reason: "Magnesium + healthy fats satisfy PMS cravings naturally",
    portion: "30g mixed nuts + 20g dark chocolate",
    calories: 280, protein: 6, carbs: 18, fats: 20, fiber: 3,
    keyNutrient: "Magnesium",
  },
  {
    id: "lut-03",
    name: "Sweet Potato + Chickpea Curry",
    emoji: "🍠", phase: "luteal", mealType: "dinner",
    reason: "Complex carbs prevent blood sugar spikes and mood swings",
    portion: "200g sweet potato + 150g chickpeas + coconut milk",
    calories: 460, protein: 14, carbs: 72, fats: 14, fiber: 14,
    keyNutrient: "Complex Carbs",
  },
  {
    id: "lut-04",
    name: "Chamomile + Honey + Warm Milk",
    emoji: "🍯", phase: "luteal", mealType: "snack",
    reason: "Chamomile reduces anxiety; tryptophan in milk aids sleep",
    portion: "250ml warm milk + 1 tsp honey + chamomile",
    calories: 160, protein: 8, carbs: 22, fats: 4, fiber: 0,
    keyNutrient: "Tryptophan",
  },
  {
    id: "lut-05",
    name: "Salmon + Roasted Vegetables",
    emoji: "🐟", phase: "luteal", mealType: "dinner",
    reason: "Omega-3 reduces PMS symptoms and supports mood",
    portion: "180g salmon + 200g mixed roasted veg",
    calories: 480, protein: 38, carbs: 24, fats: 24, fiber: 8,
    keyNutrient: "Omega-3",
  },
  {
    id: "lut-06",
    name: "Walnut + Banana Smoothie",
    emoji: "🥤", phase: "luteal", mealType: "snack",
    reason: "Walnuts support serotonin production, banana boosts mood",
    portion: "30g walnuts + 1 banana + 200ml oat milk",
    calories: 320, protein: 8, carbs: 42, fats: 14, fiber: 5,
    keyNutrient: "Serotonin Support",
  },
  {
    id: "lut-07",
    name: "Pumpkin Oat Porridge",
    emoji: "🎃", phase: "luteal", mealType: "breakfast",
    reason: "Zinc from pumpkin seeds + oats stabilise blood sugar",
    portion: "80g oats + 50g pumpkin seeds + cinnamon",
    calories: 440, protein: 16, carbs: 56, fats: 18, fiber: 8,
    keyNutrient: "Zinc + Fiber",
  },
  {
    id: "lut-08",
    name: "Lentil + Vegetable Bowl",
    emoji: "🥦", phase: "luteal", mealType: "lunch",
    reason: "Iron + folate + fiber reduce fatigue and bloating",
    portion: "150g lentils + 200g roasted veg + tahini",
    calories: 420, protein: 20, carbs: 58, fats: 10, fiber: 16,
    keyNutrient: "Iron + Fiber",
  },
  {
    id: "lut-09",
    name: "Turkey + Spinach Wrap",
    emoji: "🌯", phase: "luteal", mealType: "lunch",
    reason: "Tryptophan in turkey converts to serotonin, improving mood",
    portion: "1 wrap + 120g turkey + spinach + hummus",
    calories: 390, protein: 30, carbs: 40, fats: 10, fiber: 6,
    keyNutrient: "Tryptophan",
  },
  {
    id: "lut-10",
    name: "Baked Oatmeal Squares",
    emoji: "🍪", phase: "luteal", mealType: "snack",
    reason: "Satisfies sweet cravings with stable energy — no blood sugar spike",
    portion: "2 squares (80g total)",
    calories: 260, protein: 7, carbs: 40, fats: 8, fiber: 4,
    keyNutrient: "Stable Carbs",
  },
  {
    id: "lut-11",
    name: "Egg + Veggie Frittata",
    emoji: "🥚", phase: "luteal", mealType: "dinner",
    reason: "B vitamins + choline support hormone detox in liver",
    portion: "3 eggs + 150g vegetables + feta",
    calories: 360, protein: 26, carbs: 12, fats: 22, fiber: 4,
    keyNutrient: "B Vitamins + Choline",
  },
  {
    id: "lut-12",
    name: "Tahini + Apple Slices",
    emoji: "🍏", phase: "luteal", mealType: "snack",
    reason: "Sesame packed with calcium + magnesium, apple gives fiber",
    portion: "2 tbsp tahini + 1 apple",
    calories: 240, protein: 6, carbs: 30, fats: 12, fiber: 5,
    keyNutrient: "Calcium + Magnesium",
  },
  {
    id: "lut-13",
    name: "Overnight Buckwheat Porridge",
    emoji: "🌾", phase: "luteal", mealType: "breakfast",
    reason: "Buckwheat contains rutin which reduces bloating and water retention",
    portion: "80g buckwheat + 200ml milk + berries",
    calories: 380, protein: 14, carbs: 62, fats: 6, fiber: 6,
    keyNutrient: "Rutin + Fiber",
  },
  {
    id: "lut-14",
    name: "Hummus + Veggie Sticks",
    emoji: "🫑", phase: "luteal", mealType: "snack",
    reason: "Chickpeas provide B6 which eases PMS mood symptoms",
    portion: "80g hummus + 150g mixed veggies",
    calories: 210, protein: 8, carbs: 24, fats: 10, fiber: 8,
    keyNutrient: "Vitamin B6",
  },

  // ── MENSTRUAL — extra foods ────────────────────────────────────────────
  {
    id: "men-14",
    name: "Beef & Spinach Stir-Fry",
    emoji: "🥩", phase: "menstrual", mealType: "dinner",
    reason: "Red meat + spinach = dual iron hit to replenish period losses",
    portion: "150g beef, 100g spinach, 1 tbsp olive oil",
    calories: 380, protein: 35, carbs: 8, fats: 22, fiber: 3,
    keyNutrient: "Haem + non-haem iron",
  },
  {
    id: "men-15",
    name: "Dark Chocolate Overnight Oats",
    emoji: "🍫", phase: "menstrual", mealType: "breakfast",
    reason: "Oats stabilise blood sugar; dark chocolate provides magnesium and mood-lifting compounds",
    portion: "80g oats, 20g dark chocolate chips, 250ml oat milk",
    calories: 450, protein: 12, carbs: 68, fats: 14, fiber: 8,
    keyNutrient: "Magnesium",
  },
  {
    id: "men-16",
    name: "Ginger Turmeric Lentil Soup",
    emoji: "🍲", phase: "menstrual", mealType: "lunch",
    reason: "Ginger and turmeric are natural anti-inflammatories that reduce cramping",
    portion: "350ml bowl with 150g lentils",
    calories: 290, protein: 16, carbs: 44, fats: 5, fiber: 12,
    keyNutrient: "Curcumin + gingerol",
  },
  {
    id: "men-17",
    name: "Chamomile Banana Smoothie",
    emoji: "🍌", phase: "menstrual", mealType: "snack",
    reason: "Banana provides B6 and magnesium; chamomile calms uterine muscle spasms",
    portion: "1 banana, 200ml chamomile tea (cooled), 1 tbsp almond butter",
    calories: 220, protein: 5, carbs: 38, fats: 8, fiber: 4,
    keyNutrient: "Magnesium + B6",
  },
  {
    id: "men-18",
    name: "Sardines on Rye Bread",
    emoji: "🐟", phase: "menstrual", mealType: "lunch",
    reason: "Sardines are the highest omega-3 source by weight — directly reduces prostaglandin-driven cramps",
    portion: "1 tin sardines (120g), 2 slices rye, lemon",
    calories: 340, protein: 28, carbs: 28, fats: 12, fiber: 4,
    keyNutrient: "EPA/DHA omega-3",
  },
  {
    id: "men-19",
    name: "Warm Bone Broth",
    emoji: "🫙", phase: "menstrual", mealType: "snack",
    reason: "Mineral-rich, anti-inflammatory, and deeply nourishing during low-energy days",
    portion: "300ml mug with pinch of sea salt",
    calories: 45, protein: 9, carbs: 2, fats: 1, fiber: 0,
    keyNutrient: "Collagen + minerals",
  },

  // ── FOLLICULAR — extra foods ───────────────────────────────────────────
  {
    id: "fol-13",
    name: "Kimchi Fried Rice with Egg",
    emoji: "🍳", phase: "follicular", mealType: "breakfast",
    reason: "Fermented kimchi supports oestrogen metabolism; eggs provide choline for brain performance",
    portion: "200g rice, 100g kimchi, 2 eggs",
    calories: 490, protein: 22, carbs: 68, fats: 14, fiber: 4,
    keyNutrient: "Probiotics + choline",
  },
  {
    id: "fol-14",
    name: "Broccoli & Chicken Power Bowl",
    emoji: "🥦", phase: "follicular", mealType: "lunch",
    reason: "DIM in broccoli helps the liver detox excess oestrogen for better hormone balance",
    portion: "150g chicken, 150g broccoli, 80g quinoa",
    calories: 420, protein: 42, carbs: 38, fats: 9, fiber: 7,
    keyNutrient: "DIM + lean protein",
  },
  {
    id: "fol-15",
    name: "Flaxseed Protein Pancakes",
    emoji: "🥞", phase: "follicular", mealType: "breakfast",
    reason: "Ground flaxseed contains lignans that support healthy oestrogen levels naturally",
    portion: "3 pancakes: 2 eggs, 1 tbsp flaxseed, 30g protein powder",
    calories: 380, protein: 36, carbs: 22, fats: 14, fiber: 6,
    keyNutrient: "Lignans + protein",
  },
  {
    id: "fol-16",
    name: "Miso Glazed Salmon",
    emoji: "🍣", phase: "follicular", mealType: "dinner",
    reason: "Miso fermentation supports gut health; salmon omega-3 enhances follicular development",
    portion: "180g salmon, 1 tbsp miso, steamed bok choy",
    calories: 420, protein: 38, carbs: 12, fats: 22, fiber: 3,
    keyNutrient: "Omega-3 + probiotics",
  },
  {
    id: "fol-17",
    name: "Pumpkin Seed Trail Mix",
    emoji: "🌻", phase: "follicular", mealType: "snack",
    reason: "Pumpkin seeds are rich in zinc which supports egg quality during follicular phase",
    portion: "40g pumpkin seeds, 20g dried cranberries, 15g almonds",
    calories: 280, protein: 10, carbs: 22, fats: 18, fiber: 4,
    keyNutrient: "Zinc",
  },
  {
    id: "fol-18",
    name: "Green Goddess Smoothie",
    emoji: "🥬", phase: "follicular", mealType: "breakfast",
    reason: "Spirulina and spinach provide iron and B vitamins; banana fuels training energy",
    portion: "1 banana, 100g spinach, 1 tsp spirulina, 250ml almond milk",
    calories: 195, protein: 8, carbs: 36, fats: 3, fiber: 5,
    keyNutrient: "Spirulina + iron",
  },
  {
    id: "fol-19",
    name: "Lentil & Roasted Veg Wrap",
    emoji: "🌯", phase: "follicular", mealType: "lunch",
    reason: "Lentils provide plant protein and folate, essential for cell regeneration in the follicular phase",
    portion: "1 wholemeal wrap, 100g lentils, 120g roasted veg",
    calories: 390, protein: 18, carbs: 58, fats: 7, fiber: 12,
    keyNutrient: "Folate",
  },

  // ── OVULATION — extra foods ────────────────────────────────────────────
  {
    id: "ovu-10",
    name: "Steak & Sweet Potato",
    emoji: "🥩", phase: "ovulation", mealType: "dinner",
    reason: "Zinc from red meat supports ovulation; sweet potato carbs refuel peak training sessions",
    portion: "200g sirloin, 200g sweet potato, salad",
    calories: 580, protein: 48, carbs: 42, fats: 18, fiber: 6,
    keyNutrient: "Zinc + complex carbs",
  },
  {
    id: "ovu-11",
    name: "Pre-Workout Banana & PB Toast",
    emoji: "🍌", phase: "ovulation", mealType: "snack",
    reason: "Fast carbs from banana fuel peak-intensity sessions; PB provides sustained energy",
    portion: "2 slices sourdough, 2 tbsp peanut butter, 1 banana",
    calories: 480, protein: 14, carbs: 68, fats: 16, fiber: 6,
    keyNutrient: "Fast + slow carbs",
  },
  {
    id: "ovu-12",
    name: "Chicken Burrito Bowl",
    emoji: "🌯", phase: "ovulation", mealType: "lunch",
    reason: "High protein + carb combo designed for peak performance days — maximum muscle fuel",
    portion: "200g chicken, 150g rice, beans, salsa, avocado",
    calories: 620, protein: 52, carbs: 58, fats: 18, fiber: 10,
    keyNutrient: "Complete protein + carbs",
  },
  {
    id: "ovu-13",
    name: "Post-Workout Recovery Shake",
    emoji: "🥤", phase: "ovulation", mealType: "snack",
    reason: "30g protein + fast carbs within 30 min post-workout maximises muscle protein synthesis",
    portion: "30g whey protein, 1 banana, 250ml milk, 1 tbsp honey",
    calories: 420, protein: 36, carbs: 52, fats: 5, fiber: 2,
    keyNutrient: "Whey protein + leucine",
  },
  {
    id: "ovu-14",
    name: "Tuna Poke Bowl",
    emoji: "🐟", phase: "ovulation", mealType: "lunch",
    reason: "Raw tuna is dense in zinc and omega-3 which support peak ovulation and recovery",
    portion: "150g tuna, 150g rice, edamame, cucumber, sesame",
    calories: 490, protein: 42, carbs: 48, fats: 12, fiber: 5,
    keyNutrient: "Zinc + omega-3",
  },
  {
    id: "ovu-15",
    name: "High-Protein French Toast",
    emoji: "🍞", phase: "ovulation", mealType: "breakfast",
    reason: "Eggs provide complete protein; sourdough carbs fuel morning training sessions",
    portion: "3 eggs, 2 slices sourdough, 1 tsp maple syrup",
    calories: 420, protein: 28, carbs: 38, fats: 16, fiber: 3,
    keyNutrient: "Complete protein",
  },

  // ── LUTEAL — extra foods ───────────────────────────────────────────────
  {
    id: "lut-14",
    name: "Baked Sweet Potato with Cottage Cheese",
    emoji: "🍠", phase: "luteal", mealType: "lunch",
    reason: "Sweet potato stabilises blood sugar; cottage cheese provides casein protein that reduces cravings",
    portion: "200g sweet potato, 150g cottage cheese, chives",
    calories: 320, protein: 24, carbs: 42, fats: 4, fiber: 5,
    keyNutrient: "Casein + resistant starch",
  },
  {
    id: "lut-15",
    name: "Turkey & Avocado Lettuce Wraps",
    emoji: "🥑", phase: "luteal", mealType: "lunch",
    reason: "Turkey is the richest source of tryptophan — a direct precursor to serotonin for PMS mood",
    portion: "150g turkey, ½ avocado, 4 lettuce leaves, tomato",
    calories: 360, protein: 34, carbs: 10, fats: 20, fiber: 6,
    keyNutrient: "Tryptophan + healthy fats",
  },
  {
    id: "lut-16",
    name: "Magnesium Brownie Bites",
    emoji: "🍫", phase: "luteal", mealType: "snack",
    reason: "Dark chocolate + almonds + black beans = triple magnesium hit that directly eases PMS cramps",
    portion: "2 brownie bites (made with black beans, cacao, almond flour)",
    calories: 180, protein: 6, carbs: 22, fats: 9, fiber: 5,
    keyNutrient: "Magnesium",
  },
  {
    id: "lut-17",
    name: "Salmon Pasta with Cream Sauce",
    emoji: "🍝", phase: "luteal", mealType: "dinner",
    reason: "Pasta provides stable carbs for luteal energy needs; salmon omega-3 reduces prostaglandins",
    portion: "80g pasta, 150g salmon, 50ml cream, spinach",
    calories: 580, protein: 36, carbs: 55, fats: 22, fiber: 4,
    keyNutrient: "Omega-3 + complex carbs",
  },
  {
    id: "lut-18",
    name: "Banana Almond Overnight Oats",
    emoji: "🌙", phase: "luteal", mealType: "breakfast",
    reason: "Slow-release carbs prevent the morning energy crash that is common in the luteal phase",
    portion: "80g oats, 1 banana, 2 tbsp almond butter, 200ml almond milk",
    calories: 490, protein: 14, carbs: 65, fats: 18, fiber: 9,
    keyNutrient: "Magnesium + B6",
  },
  {
    id: "lut-19",
    name: "Pumpkin Curry",
    emoji: "🎃", phase: "luteal", mealType: "dinner",
    reason: "Pumpkin is rich in beta-carotene and zinc; turmeric reduces inflammation and PMS severity",
    portion: "300g pumpkin curry, 150g brown rice",
    calories: 420, protein: 12, carbs: 62, fats: 14, fiber: 8,
    keyNutrient: "Beta-carotene + zinc",
  },
  {
    id: "lut-20",
    name: "Walnut & Date Energy Balls",
    emoji: "🌰", phase: "luteal", mealType: "snack",
    reason: "Walnuts are highest plant source of omega-3; dates provide instant energy to combat luteal fatigue",
    portion: "3 balls: walnuts, dates, oats, cacao",
    calories: 240, protein: 5, carbs: 32, fats: 12, fiber: 4,
    keyNutrient: "ALA omega-3",
  },
  {
    id: "lut-21",
    name: "Chamomile Honey Latte",
    emoji: "🍵", phase: "luteal", mealType: "snack",
    reason: "Chamomile reduces anxiety and uterine spasms; warm drinks soothe luteal bloating",
    portion: "300ml oat milk, 2 chamomile tea bags, 1 tsp honey",
    calories: 110, protein: 3, carbs: 20, fats: 2, fiber: 0,
    keyNutrient: "Apigenin (calming)",
  },

  // ── MENSTRUAL — extra meals ───────────────────────────────────────────────
  {
    id: "men-11", name: "Beef & Vegetable Stew", emoji: "🍲",
    phase: "menstrual", mealType: "dinner",
    reason: "Haem iron from beef replaces blood loss; vegetables add anti-inflammatory compounds",
    portion: "350g stew (1.5 cups)",
    calories: 390, protein: 32, carbs: 28, fats: 14, fiber: 6,
    keyNutrient: "Haem Iron",
  },
  {
    id: "men-12", name: "Scrambled Eggs + Spinach on Rye", emoji: "🍳",
    phase: "menstrual", mealType: "breakfast",
    reason: "Iron from eggs and spinach; B12 supports energy during blood loss",
    portion: "3 eggs + 60g spinach + 1 slice rye bread",
    calories: 320, protein: 24, carbs: 22, fats: 16, fiber: 4,
    keyNutrient: "Iron · B12",
  },
  {
    id: "men-13", name: "Miso Soup + Tofu + Seaweed", emoji: "🍜",
    phase: "menstrual", mealType: "lunch",
    reason: "Iodine from seaweed supports thyroid; tofu provides plant iron and protein",
    portion: "400ml miso soup + 100g tofu",
    calories: 185, protein: 14, carbs: 12, fats: 8, fiber: 3,
    keyNutrient: "Iodine · Plant Iron",
  },
  {
    id: "men-14", name: "Banana + Almond Butter Oats", emoji: "🥣",
    phase: "menstrual", mealType: "breakfast",
    reason: "Magnesium from almonds eases cramps; banana B6 lifts mood; oats provide steady energy",
    portion: "60g oats + 1 banana + 2 tbsp almond butter",
    calories: 460, protein: 14, carbs: 62, fats: 18, fiber: 8,
    keyNutrient: "Magnesium · B6",
  },
  {
    id: "men-15", name: "Pumpkin Soup + Crusty Bread", emoji: "🎃",
    phase: "menstrual", mealType: "lunch",
    reason: "Beta-carotene reduces inflammation; warming soup soothes cramps",
    portion: "350ml soup + 1 slice bread",
    calories: 280, protein: 6, carbs: 45, fats: 8, fiber: 5,
    keyNutrient: "Beta-carotene · Magnesium",
  },

  // ── FOLLICULAR — extra meals ──────────────────────────────────────────────
  {
    id: "fol-11", name: "Smoked Salmon + Avocado Toast", emoji: "🥑",
    phase: "follicular", mealType: "breakfast",
    reason: "Omega-3 and healthy fats support rising oestrogen; folate in avocado aids egg development",
    portion: "2 slices sourdough + 80g smoked salmon + ½ avocado",
    calories: 490, protein: 28, carbs: 38, fats: 22, fiber: 7,
    keyNutrient: "Omega-3 · Folate",
  },
  {
    id: "fol-12", name: "Chicken & Broccoli Stir Fry + Rice", emoji: "🍱",
    phase: "follicular", mealType: "dinner",
    reason: "DIM from broccoli metabolises oestrogen; lean protein supports muscle building",
    portion: "150g chicken + 200g broccoli + 150g rice",
    calories: 510, protein: 42, carbs: 55, fats: 8, fiber: 6,
    keyNutrient: "DIM · Complete protein",
  },
  {
    id: "fol-13", name: "Berry Protein Smoothie Bowl", emoji: "🍓",
    phase: "follicular", mealType: "breakfast",
    reason: "Antioxidants protect follicles; protein supports muscle repair after training",
    portion: "200g mixed berries + 30g protein powder + 100g Greek yogurt",
    calories: 320, protein: 32, carbs: 35, fats: 4, fiber: 7,
    keyNutrient: "Antioxidants · Protein",
  },
  {
    id: "fol-14", name: "Lentil & Feta Salad", emoji: "🥗",
    phase: "follicular", mealType: "lunch",
    reason: "Plant iron and folate support egg development; feta adds calcium and protein",
    portion: "200g cooked lentils + 50g feta + mixed greens",
    calories: 380, protein: 22, carbs: 44, fats: 12, fiber: 14,
    keyNutrient: "Folate · Plant Iron",
  },
  {
    id: "fol-15", name: "Prawn & Vegetable Pasta", emoji: "🍝",
    phase: "follicular", mealType: "dinner",
    reason: "Iodine from prawns supports thyroid; wholemeal pasta gives sustained energy",
    portion: "150g prawns + 120g wholemeal pasta + vegetables",
    calories: 485, protein: 36, carbs: 58, fats: 8, fiber: 8,
    keyNutrient: "Iodine · Selenium",
  },
  {
    id: "fol-16", name: "Mushroom & Spinach Omelette", emoji: "🍳",
    phase: "follicular", mealType: "breakfast",
    reason: "Vitamin D from mushrooms supports oestrogen; iron from spinach boosts energy",
    portion: "3 eggs + 100g mushrooms + 60g spinach",
    calories: 295, protein: 26, carbs: 6, fats: 18, fiber: 3,
    keyNutrient: "Vitamin D · Iron",
  },

  // ── OVULATION — extra meals ───────────────────────────────────────────────
  {
    id: "ov-09", name: "Tuna Niçoise Salad", emoji: "🥗",
    phase: "ovulation", mealType: "lunch",
    reason: "Omega-3 protects egg quality; vegetables provide antioxidants at peak fertility",
    portion: "150g tuna + egg + olives + green beans + tomato",
    calories: 420, protein: 38, carbs: 18, fats: 20, fiber: 5,
    keyNutrient: "Omega-3 · Selenium",
  },
  {
    id: "ov-10", name: "Beef Steak + Sweet Potato Mash", emoji: "🥩",
    phase: "ovulation", mealType: "dinner",
    reason: "Zinc and iron support the LH surge and ovulation; sweet potato gives quality carbs",
    portion: "180g sirloin steak + 200g sweet potato",
    calories: 560, protein: 44, carbs: 42, fats: 16, fiber: 6,
    keyNutrient: "Zinc · Iron",
  },
  {
    id: "ov-11", name: "Açaí Bowl + Seeds", emoji: "🫐",
    phase: "ovulation", mealType: "breakfast",
    reason: "Açaí is rich in antioxidants that protect egg quality; seeds add zinc and vitamin E",
    portion: "200g açaí + mixed toppings + 1 tbsp pumpkin seeds",
    calories: 380, protein: 8, carbs: 48, fats: 18, fiber: 9,
    keyNutrient: "Antioxidants · Zinc",
  },
  {
    id: "ov-12", name: "Grilled Chicken Caesar Wrap", emoji: "🌯",
    phase: "ovulation", mealType: "lunch",
    reason: "Lean protein supports peak physical performance; romaine is rich in folate",
    portion: "150g chicken + wholemeal wrap + romaine + light dressing",
    calories: 450, protein: 40, carbs: 38, fats: 12, fiber: 4,
    keyNutrient: "Protein · Folate",
  },
  {
    id: "ov-13", name: "Shrimp Tacos + Mango Salsa", emoji: "🌮",
    phase: "ovulation", mealType: "dinner",
    reason: "Zinc from shrimp supports ovulation; mango vitamin C boosts immunity at peak",
    portion: "150g shrimp + 2 corn tortillas + mango salsa",
    calories: 420, protein: 30, carbs: 50, fats: 9, fiber: 5,
    keyNutrient: "Zinc · Vitamin C",
  },

  // ── LUTEAL — extra meals ──────────────────────────────────────────────────
  {
    id: "lut-11", name: "Turkey & Sweet Potato Bowl", emoji: "🥣",
    phase: "luteal", mealType: "lunch",
    reason: "Tryptophan in turkey converts to serotonin; sweet potato satisfies carb cravings",
    portion: "150g turkey mince + 200g sweet potato + greens",
    calories: 450, protein: 36, carbs: 48, fats: 8, fiber: 7,
    keyNutrient: "Tryptophan · B6",
  },
  {
    id: "lut-12", name: "Salmon Teriyaki + Brown Rice", emoji: "🍱",
    phase: "luteal", mealType: "dinner",
    reason: "Omega-3 reduces PMS inflammation; B vitamins in salmon support mood stability",
    portion: "150g salmon + 150g brown rice + vegetables",
    calories: 520, protein: 36, carbs: 55, fats: 16, fiber: 5,
    keyNutrient: "Omega-3 · B vitamins",
  },
  {
    id: "lut-13", name: "Chickpea & Spinach Curry", emoji: "🍛",
    phase: "luteal", mealType: "dinner",
    reason: "Chickpea iron and fibre reduce PMS; turmeric in curry is strongly anti-inflammatory",
    portion: "300g curry + 150g basmati rice",
    calories: 480, protein: 18, carbs: 72, fats: 10, fiber: 14,
    keyNutrient: "Iron · Curcumin",
  },
  {
    id: "lut-14", name: "French Toast + Berries", emoji: "🍞",
    phase: "luteal", mealType: "breakfast",
    reason: "Satisfies carb and sweet cravings; eggs provide choline for brain fog",
    portion: "2 slices whole grain + 2 eggs + 100g berries + maple syrup",
    calories: 420, protein: 18, carbs: 58, fats: 12, fiber: 5,
    keyNutrient: "Choline · B6",
  },
  {
    id: "lut-15", name: "Stuffed Bell Peppers (Beef & Rice)", emoji: "🫑",
    phase: "luteal", mealType: "dinner",
    reason: "Zinc from beef stabilises luteal phase; vitamin C from pepper boosts iron absorption",
    portion: "2 bell peppers + 100g beef mince + 80g rice",
    calories: 440, protein: 30, carbs: 45, fats: 14, fiber: 7,
    keyNutrient: "Zinc · Vitamin C",
  },
  {
    id: "lut-16", name: "Peanut Butter Banana Smoothie", emoji: "🥤",
    phase: "luteal", mealType: "snack",
    reason: "Magnesium from peanut butter eases PMS; banana B6 supports serotonin production",
    portion: "1 banana + 2 tbsp peanut butter + 250ml oat milk",
    calories: 380, protein: 12, carbs: 52, fats: 16, fiber: 5,
    keyNutrient: "Magnesium · B6",
  },
  {
    id: "lut-17", name: "Cottage Cheese + Walnuts + Honey", emoji: "🥛",
    phase: "luteal", mealType: "snack",
    reason: "Casein protein keeps you full through cravings; walnuts reduce PMS inflammation",
    portion: "200g cottage cheese + 20g walnuts + 1 tsp honey",
    calories: 310, protein: 28, carbs: 14, fats: 16, fiber: 1,
    keyNutrient: "Casein · Omega-3",
  },
];

// ── Helper functions ───────────────────────────────────────────────────────

export function getFoodsByPhase(phase: Phase): FoodItem[] {
  return FOOD_LIBRARY.filter(f => f.phase === phase);
}

export function getFoodsByPhaseAndType(phase: Phase, type: MealType): FoodItem[] {
  return FOOD_LIBRARY.filter(f => f.phase === phase && f.mealType === type);
}

export const MEAL_TYPE_ORDER: MealType[] = ["breakfast", "lunch", "dinner", "snack"];

export const MEAL_TYPE_LABELS: Record<MealType, { label: string; emoji: string; bg: string; text: string }> = {
  breakfast: { label: "Breakfast", emoji: "🌅", bg: "#FEF3C7", text: "#D97706" },
  lunch:     { label: "Lunch",     emoji: "☀️", bg: "#D1FAE5", text: "#059669" },
  dinner:    { label: "Dinner",    emoji: "🌙", bg: "#EDE9FE", text: "#7C3AED" },
  snack:     { label: "Snack",     emoji: "🍎", bg: "#FCE7F3", text: "#DB2777" },
};
