// lib/quickFoods.ts — Generic food database with phase recommendations
export type Phase = "menstrual" | "follicular" | "ovulation" | "luteal";

export interface QuickFood {
  id: string;
  name: string;
  emoji: string;
  category: "fruit" | "vegetable" | "protein" | "grain" | "dairy" | "fat" | "drink" | "other";
  per100g: { calories: number; protein: number; carbs: number; fats: number; fiber?: number };
  phases: Phase[];
  keyNutrient: string;
  phaseReasons: Partial<Record<Phase, string>>;
}

export const QUICK_FOODS: QuickFood[] = [
  // FRUIT
  { id:"apple", name:"Apple", emoji:"🍎", category:"fruit", per100g:{calories:52,protein:0.3,carbs:14,fats:0.2,fiber:2.4}, phases:["follicular","luteal"], keyNutrient:"Quercetin · Fibre · Vitamin C", phaseReasons:{follicular:"Quercetin supports oestrogen metabolism as hormone levels rise",luteal:"Soluble fibre helps manage PMS bloating and stabilise blood sugar"} },
  { id:"banana", name:"Banana", emoji:"🍌", category:"fruit", per100g:{calories:89,protein:1.1,carbs:23,fats:0.3,fiber:2.6}, phases:["menstrual","luteal"], keyNutrient:"Vitamin B6 · Magnesium · Potassium", phaseReasons:{menstrual:"Magnesium eases cramps and mood; potassium reduces bloating",luteal:"B6 directly reduces PMS symptoms and supports serotonin production"} },
  { id:"strawberry", name:"Strawberry", emoji:"🍓", category:"fruit", per100g:{calories:32,protein:0.7,carbs:7.7,fats:0.3,fiber:2.0}, phases:["follicular","ovulation"], keyNutrient:"Vitamin C · Folate · Antioxidants", phaseReasons:{follicular:"Folate supports egg development; Vitamin C boosts collagen and energy",ovulation:"Antioxidants protect the egg from oxidative stress at peak fertility"} },
  { id:"orange", name:"Orange", emoji:"🍊", category:"fruit", per100g:{calories:47,protein:0.9,carbs:12,fats:0.1,fiber:2.4}, phases:["menstrual","follicular"], keyNutrient:"Vitamin C · Folate · Flavonoids", phaseReasons:{menstrual:"Vitamin C enhances iron absorption to replenish what's lost during bleeding",follicular:"Folate supports cell renewal; flavonoids reduce inflammation as energy returns"} },
  { id:"pomegranate", name:"Pomegranate", emoji:"🍑", category:"fruit", per100g:{calories:83,protein:1.7,carbs:19,fats:1.2,fiber:4.0}, phases:["follicular","ovulation"], keyNutrient:"Punicalagins · Folate · Antioxidants", phaseReasons:{follicular:"Supports oestrogen production and uterine lining development",ovulation:"Strong antioxidants protect egg quality at peak fertility window"} },
  { id:"blueberry", name:"Blueberry", emoji:"🫐", category:"fruit", per100g:{calories:57,protein:0.7,carbs:14,fats:0.3,fiber:2.4}, phases:["menstrual","ovulation","luteal"], keyNutrient:"Anthocyanins · Vitamin C · Fibre", phaseReasons:{menstrual:"Anti-inflammatory anthocyanins reduce cramping and pain",ovulation:"Antioxidants support egg quality during the fertility window",luteal:"Helps regulate mood and reduce PMS-related anxiety"} },
  { id:"mango", name:"Mango", emoji:"🥭", category:"fruit", per100g:{calories:60,protein:0.8,carbs:15,fats:0.4,fiber:1.6}, phases:["follicular","ovulation"], keyNutrient:"Vitamin C · Beta-carotene · Folate", phaseReasons:{follicular:"Beta-carotene supports Vitamin A for follicle development",ovulation:"High Vitamin C supports peak energy and immune function"} },
  { id:"pineapple", name:"Pineapple", emoji:"🍍", category:"fruit", per100g:{calories:50,protein:0.5,carbs:13,fats:0.1,fiber:1.4}, phases:["follicular","ovulation"], keyNutrient:"Bromelain · Vitamin C · Manganese", phaseReasons:{follicular:"Bromelain is anti-inflammatory, supports uterine lining receptivity",ovulation:"Manganese supports bone health and hormone balance at peak phase"} },
  { id:"watermelon", name:"Watermelon", emoji:"🍉", category:"fruit", per100g:{calories:30,protein:0.6,carbs:7.6,fats:0.2,fiber:0.4}, phases:["menstrual","ovulation"], keyNutrient:"Lycopene · Citrulline · Vitamin C", phaseReasons:{menstrual:"High water content reduces bloating; lycopene is anti-inflammatory",ovulation:"Citrulline improves blood flow and supports peak performance energy"} },
  { id:"grapes", name:"Grapes", emoji:"🍇", category:"fruit", per100g:{calories:69,protein:0.7,carbs:18,fats:0.2,fiber:0.9}, phases:["follicular","luteal"], keyNutrient:"Resveratrol · Vitamin K · Antioxidants", phaseReasons:{follicular:"Resveratrol supports oestrogen metabolism and energy levels",luteal:"Antioxidants reduce oxidative stress during the premenstrual phase"} },
  { id:"peach", name:"Peach", emoji:"🍑", category:"fruit", per100g:{calories:39,protein:0.9,carbs:10,fats:0.3,fiber:1.5}, phases:["follicular","ovulation"], keyNutrient:"Vitamin C · Beta-carotene · Potassium", phaseReasons:{follicular:"Beta-carotene supports oestrogen production and skin health",ovulation:"Vitamin C and potassium support peak energy and recovery"} },
  { id:"pear", name:"Pear", emoji:"🍐", category:"fruit", per100g:{calories:57,protein:0.4,carbs:15,fats:0.1,fiber:3.1}, phases:["luteal","menstrual"], keyNutrient:"Fibre · Copper · Vitamin C", phaseReasons:{luteal:"High fibre supports gut health and reduces bloating before period",menstrual:"Copper supports iron metabolism; gentle energy during low phase"} },
  { id:"kiwi", name:"Kiwi", emoji:"🥝", category:"fruit", per100g:{calories:61,protein:1.1,carbs:15,fats:0.5,fiber:3.0}, phases:["follicular","ovulation"], keyNutrient:"Vitamin C · Vitamin K · Folate", phaseReasons:{follicular:"Folate supports DNA synthesis; Vitamin C boosts collagen and immunity",ovulation:"High Vitamin C protects egg from oxidative damage at peak fertility"} },
  { id:"cherry", name:"Cherry", emoji:"🍒", category:"fruit", per100g:{calories:63,protein:1.1,carbs:16,fats:0.2,fiber:2.1}, phases:["menstrual","luteal"], keyNutrient:"Melatonin · Anthocyanins · Vitamin C", phaseReasons:{menstrual:"Natural melatonin improves sleep; anthocyanins reduce cramp pain",luteal:"Reduces inflammation and supports better sleep before period"} },
  { id:"lemon", name:"Lemon", emoji:"🍋", category:"fruit", per100g:{calories:29,protein:1.1,carbs:9.3,fats:0.3,fiber:2.8}, phases:["menstrual","follicular"], keyNutrient:"Vitamin C · Flavonoids · Citric acid", phaseReasons:{menstrual:"Vitamin C boosts iron absorption; flavonoids reduce menstrual pain",follicular:"Citric acid supports digestion and energy as hormone levels rise"} },
  { id:"raspberry", name:"Raspberry", emoji:"🍓", category:"fruit", per100g:{calories:52,protein:1.2,carbs:12,fats:0.7,fiber:6.5}, phases:["menstrual","follicular"], keyNutrient:"Ellagic acid · Fibre · Vitamin C", phaseReasons:{menstrual:"Ellagic acid and anti-inflammatory compounds ease cramps and pain",follicular:"High fibre supports oestrogen clearance and gut health"} },
  { id:"fig", name:"Fig", emoji:"🍈", category:"fruit", per100g:{calories:74,protein:0.8,carbs:19,fats:0.3,fiber:2.9}, phases:["menstrual","luteal"], keyNutrient:"Iron · Calcium · Potassium", phaseReasons:{menstrual:"Iron helps replenish blood loss; calcium reduces cramping",luteal:"Calcium and potassium reduce PMS symptoms and water retention"} },
  { id:"date", name:"Date (Medjool)", emoji:"🟤", category:"fruit", per100g:{calories:277,protein:1.8,carbs:75,fats:0.2,fiber:6.7}, phases:["menstrual","luteal"], keyNutrient:"Iron · Magnesium · Natural sugars", phaseReasons:{menstrual:"Iron replenishes blood loss; magnesium eases cramps and fatigue",luteal:"Natural sugars satisfy sweet cravings; magnesium supports mood"} },

  // VEGETABLES
  { id:"spinach", name:"Spinach", emoji:"🥬", category:"vegetable", per100g:{calories:23,protein:2.9,carbs:3.6,fats:0.4,fiber:2.2}, phases:["menstrual","follicular"], keyNutrient:"Iron · Folate · Magnesium", phaseReasons:{menstrual:"Iron replenishes blood loss; magnesium reduces cramping and fatigue",follicular:"Folate supports egg development and DNA synthesis as cycle rebuilds"} },
  { id:"broccoli", name:"Broccoli", emoji:"🥦", category:"vegetable", per100g:{calories:34,protein:2.8,carbs:7.0,fats:0.4,fiber:2.6}, phases:["follicular","ovulation","luteal"], keyNutrient:"DIM · Vitamin C · Folate", phaseReasons:{follicular:"DIM (diindolylmethane) helps metabolise oestrogen efficiently",ovulation:"High Vitamin C and folate support peak fertility and immunity",luteal:"Fibre and DIM help clear excess oestrogen, reducing PMS bloating"} },
  { id:"tomato", name:"Tomato", emoji:"🍅", category:"vegetable", per100g:{calories:18,protein:0.9,carbs:3.9,fats:0.2,fiber:1.2}, phases:["follicular","ovulation"], keyNutrient:"Lycopene · Vitamin C · Potassium", phaseReasons:{follicular:"Lycopene protects cells during rapid growth phase",ovulation:"Vitamin C and potassium support peak energy and hormone activity"} },
  { id:"cucumber", name:"Cucumber", emoji:"🥒", category:"vegetable", per100g:{calories:15,protein:0.7,carbs:3.6,fats:0.1,fiber:0.5}, phases:["menstrual","luteal"], keyNutrient:"Water · Silica · Vitamin K", phaseReasons:{menstrual:"96% water reduces bloating and supports hydration during period",luteal:"Silica reduces water retention and puffiness before period"} },
  { id:"carrot", name:"Carrot", emoji:"🥕", category:"vegetable", per100g:{calories:41,protein:0.9,carbs:10,fats:0.2,fiber:2.8}, phases:["follicular","luteal"], keyNutrient:"Beta-carotene · Vitamin A · Fibre", phaseReasons:{follicular:"Beta-carotene supports oestrogen production and healthy follicle growth",luteal:"Fibre helps clear excess oestrogen; beta-carotene reduces PMS inflammation"} },
  { id:"bell_pepper", name:"Bell Pepper", emoji:"🫑", category:"vegetable", per100g:{calories:31,protein:1.0,carbs:6.0,fats:0.3,fiber:2.1}, phases:["follicular","ovulation"], keyNutrient:"Vitamin C · Vitamin B6 · Folate", phaseReasons:{follicular:"Exceptional Vitamin C content boosts iron absorption and energy",ovulation:"B6 and folate support hormonal balance at peak fertility"} },
  { id:"zucchini", name:"Zucchini", emoji:"🥒", category:"vegetable", per100g:{calories:17,protein:1.2,carbs:3.1,fats:0.3,fiber:1.0}, phases:["menstrual","luteal"], keyNutrient:"Potassium · Vitamin C · Folate", phaseReasons:{menstrual:"Potassium reduces cramps and bloating; easy on digestion during period",luteal:"Light and hydrating, reduces water retention before period"} },
  { id:"kale", name:"Kale", emoji:"🥬", category:"vegetable", per100g:{calories:49,protein:4.3,carbs:9.0,fats:0.9,fiber:3.6}, phases:["menstrual","follicular","luteal"], keyNutrient:"Iron · Calcium · Vitamin K · DIM", phaseReasons:{menstrual:"Iron and calcium replenish what's lost; reduces menstrual cramps",follicular:"DIM supports healthy oestrogen metabolism for clean hormone cycle",luteal:"Calcium reduces PMS symptoms; fibre supports oestrogen clearance"} },
  { id:"onion", name:"Onion", emoji:"🧅", category:"vegetable", per100g:{calories:40,protein:1.1,carbs:9.3,fats:0.1,fiber:1.7}, phases:["follicular","ovulation"], keyNutrient:"Quercetin · Sulphur compounds · Chromium", phaseReasons:{follicular:"Quercetin supports oestrogen metabolism and reduces inflammation",ovulation:"Sulphur compounds support liver detox during hormonal peak"} },
  { id:"garlic", name:"Garlic", emoji:"🧄", category:"vegetable", per100g:{calories:149,protein:6.4,carbs:33,fats:0.5,fiber:2.1}, phases:["menstrual","follicular"], keyNutrient:"Allicin · Selenium · Vitamin B6", phaseReasons:{menstrual:"Allicin has anti-inflammatory properties that reduce period cramps",follicular:"Selenium supports thyroid function and hormone production"} },
  { id:"sweet_potato", name:"Sweet Potato", emoji:"🍠", category:"vegetable", per100g:{calories:86,protein:1.6,carbs:20,fats:0.1,fiber:3.0}, phases:["menstrual","luteal"], keyNutrient:"Beta-carotene · Magnesium · Potassium", phaseReasons:{menstrual:"Magnesium reduces cramps; complex carbs provide steady energy during fatigue",luteal:"Satisfies carb cravings healthily; potassium reduces bloating"} },
  { id:"potato", name:"Potato", emoji:"🥔", category:"vegetable", per100g:{calories:77,protein:2.0,carbs:17,fats:0.1,fiber:2.2}, phases:["menstrual","luteal"], keyNutrient:"Potassium · Vitamin B6 · Resistant starch", phaseReasons:{menstrual:"Potassium reduces cramping; easy comfort food when energy is low",luteal:"B6 supports serotonin; resistant starch feeds beneficial gut bacteria"} },
  { id:"mushroom", name:"Mushroom", emoji:"🍄", category:"vegetable", per100g:{calories:22,protein:3.1,carbs:3.3,fats:0.3,fiber:1.0}, phases:["follicular","ovulation"], keyNutrient:"Vitamin D · Selenium · Beta-glucans", phaseReasons:{follicular:"Vitamin D supports oestrogen production and bone health",ovulation:"Selenium protects eggs from oxidative damage at peak fertility"} },
  { id:"avocado", name:"Avocado", emoji:"🥑", category:"fat", per100g:{calories:160,protein:2.0,carbs:9.0,fats:15,fiber:6.7}, phases:["menstrual","follicular","luteal"], keyNutrient:"Healthy fats · Magnesium · Potassium", phaseReasons:{menstrual:"Magnesium eases cramps; healthy fats reduce inflammation during period",follicular:"Supports hormone production; folate promotes healthy egg development",luteal:"Potassium reduces water retention; healthy fats stabilise mood hormones"} },
  { id:"corn", name:"Corn", emoji:"🌽", category:"vegetable", per100g:{calories:86,protein:3.3,carbs:19,fats:1.4,fiber:2.7}, phases:["follicular","ovulation"], keyNutrient:"Folate · Vitamin C · Thiamine", phaseReasons:{follicular:"Folate supports DNA synthesis and egg health during rebuilding phase",ovulation:"Sustained energy from complex carbs supports peak performance"} },
  { id:"lettuce", name:"Lettuce", emoji:"🥗", category:"vegetable", per100g:{calories:15,protein:1.4,carbs:2.9,fats:0.2,fiber:1.3}, phases:["menstrual","luteal"], keyNutrient:"Folate · Vitamin K · Lactucin", phaseReasons:{menstrual:"Lactucin has mild sedative properties that improve sleep and reduce pain",luteal:"Low calorie and hydrating; folate supports nervous system during PMS"} },
  { id:"cauliflower", name:"Cauliflower", emoji:"🥦", category:"vegetable", per100g:{calories:25,protein:1.9,carbs:5.0,fats:0.3,fiber:2.0}, phases:["follicular","luteal"], keyNutrient:"DIM · Vitamin C · Choline", phaseReasons:{follicular:"DIM supports healthy oestrogen metabolism early in cycle",luteal:"Choline supports liver function to clear excess hormones before period"} },
  { id:"eggplant", name:"Eggplant", emoji:"🍆", category:"vegetable", per100g:{calories:25,protein:1.0,carbs:6.0,fats:0.2,fiber:3.0}, phases:["follicular","ovulation"], keyNutrient:"Nasunin · Chlorogenic acid · Fibre", phaseReasons:{follicular:"Nasunin protects cell membranes during growth phase",ovulation:"Chlorogenic acid supports antioxidant defence at peak fertility"} },

  // PROTEIN
  { id:"chicken_breast", name:"Chicken Breast", emoji:"🍗", category:"protein", per100g:{calories:165,protein:31,carbs:0,fats:3.6}, phases:["follicular","ovulation","luteal"], keyNutrient:"Lean protein · Vitamin B6 · Selenium", phaseReasons:{follicular:"High protein supports muscle repair as energy and strength return",ovulation:"Selenium protects eggs from oxidative stress at peak performance",luteal:"B6 directly reduces PMS symptoms and supports serotonin production"} },
  { id:"chicken_thigh", name:"Chicken Thigh", emoji:"🍗", category:"protein", per100g:{calories:209,protein:26,carbs:0,fats:11}, phases:["menstrual","follicular"], keyNutrient:"Protein · Iron · Zinc", phaseReasons:{menstrual:"Iron replenishes blood loss; zinc supports immune function during period",follicular:"Higher fat content supports hormone production as cycle rebuilds"} },
  { id:"beef", name:"Beef (lean)", emoji:"🥩", category:"protein", per100g:{calories:250,protein:26,carbs:0,fats:16}, phases:["menstrual","follicular"], keyNutrient:"Haem iron · Zinc · Vitamin B12", phaseReasons:{menstrual:"Haem iron is most easily absorbed — essential to replace blood loss",follicular:"Zinc supports follicle development; B12 boosts energy production"} },
  { id:"salmon", name:"Salmon", emoji:"🐟", category:"protein", per100g:{calories:208,protein:20,carbs:0,fats:13}, phases:["menstrual","follicular","luteal"], keyNutrient:"Omega-3 · Vitamin D · Selenium", phaseReasons:{menstrual:"Omega-3 powerfully reduces inflammation and menstrual cramp severity",follicular:"Vitamin D supports oestrogen production and follicle development",luteal:"Omega-3 reduces PMS anxiety, depression, and water retention"} },
  { id:"tuna", name:"Tuna (canned)", emoji:"🐟", category:"protein", per100g:{calories:116,protein:26,carbs:0,fats:1.0}, phases:["follicular","ovulation"], keyNutrient:"Lean protein · Selenium · Vitamin D", phaseReasons:{follicular:"Lean high protein supports muscle building during peak energy phase",ovulation:"Selenium and Vitamin D support egg quality and immune function"} },
  { id:"egg", name:"Egg", emoji:"🥚", category:"protein", per100g:{calories:155,protein:13,carbs:1.1,fats:11}, phases:["follicular","ovulation","luteal"], keyNutrient:"Choline · Vitamin D · Complete protein", phaseReasons:{follicular:"Choline is essential for egg development and DNA methylation",ovulation:"Complete amino acid profile supports peak performance",luteal:"Vitamin D and choline support mood regulation before period"} },
  { id:"turkey", name:"Turkey", emoji:"🦃", category:"protein", per100g:{calories:189,protein:29,carbs:0,fats:7.4}, phases:["follicular","luteal"], keyNutrient:"Tryptophan · Selenium · Lean protein", phaseReasons:{follicular:"High protein supports muscle repair; selenium boosts immunity",luteal:"Tryptophan converts to serotonin, directly improving PMS mood symptoms"} },
  { id:"shrimp", name:"Shrimp", emoji:"🦐", category:"protein", per100g:{calories:99,protein:24,carbs:0.2,fats:0.3}, phases:["follicular","ovulation"], keyNutrient:"Iodine · Selenium · Lean protein", phaseReasons:{follicular:"Iodine supports thyroid function which regulates cycle hormones",ovulation:"Selenium protects egg quality; ultra-lean protein supports performance"} },
  { id:"tofu", name:"Tofu", emoji:"⬜", category:"protein", per100g:{calories:76,protein:8.1,carbs:1.9,fats:4.8}, phases:["follicular","ovulation"], keyNutrient:"Phytoestrogens · Calcium · Iron", phaseReasons:{follicular:"Phytoestrogens gently support oestrogen activity as hormone levels rise",ovulation:"Calcium and iron support peak bone density and circulation"} },
  { id:"tempeh", name:"Tempeh", emoji:"🟫", category:"protein", per100g:{calories:193,protein:19,carbs:9.4,fats:11}, phases:["follicular","luteal"], keyNutrient:"Probiotics · Phytoestrogens · Iron", phaseReasons:{follicular:"Fermentation improves gut microbiome which supports oestrogen balance",luteal:"Probiotics reduce bloating and PMS digestive symptoms"} },
  { id:"sardine", name:"Sardine", emoji:"🐟", category:"protein", per100g:{calories:208,protein:25,carbs:0,fats:11}, phases:["menstrual","luteal"], keyNutrient:"Omega-3 · Calcium · Vitamin D", phaseReasons:{menstrual:"Omega-3 strongly reduces menstrual cramps; calcium eases muscle tension",luteal:"Anti-inflammatory omega-3 reduces PMS symptoms and mood swings"} },
  { id:"pork_loin", name:"Pork Loin", emoji:"🥩", category:"protein", per100g:{calories:242,protein:27,carbs:0,fats:14}, phases:["follicular","ovulation"], keyNutrient:"Thiamine · Selenium · Zinc", phaseReasons:{follicular:"Thiamine supports energy metabolism as cycle rebuilds strength",ovulation:"Zinc and selenium support peak performance and immune function"} },
  { id:"cod", name:"Cod", emoji:"🐟", category:"protein", per100g:{calories:82,protein:18,carbs:0,fats:0.7}, phases:["follicular","ovulation"], keyNutrient:"Iodine · Lean protein · Vitamin B12", phaseReasons:{follicular:"Iodine supports thyroid health which regulates menstrual cycle",ovulation:"Extremely lean protein supports peak performance without heaviness"} },

  // GRAINS
  { id:"oats", name:"Oats", emoji:"🌾", category:"grain", per100g:{calories:389,protein:17,carbs:66,fats:7.0,fiber:10}, phases:["menstrual","luteal"], keyNutrient:"Beta-glucan · Iron · Magnesium", phaseReasons:{menstrual:"Complex carbs steady blood sugar; iron replenishes period blood loss",luteal:"Beta-glucan satisfies carb cravings and reduces PMS mood swings"} },
  { id:"brown_rice", name:"Brown Rice", emoji:"🍚", category:"grain", per100g:{calories:216,protein:5.0,carbs:45,fats:1.8,fiber:3.5}, phases:["luteal","menstrual"], keyNutrient:"Magnesium · Selenium · B vitamins", phaseReasons:{luteal:"Magnesium reduces PMS; slow carbs stabilise blood sugar and mood",menstrual:"B vitamins support energy production during low phase"} },
  { id:"white_rice", name:"White Rice", emoji:"🍚", category:"grain", per100g:{calories:204,protein:4.3,carbs:45,fats:0.4,fiber:0.6}, phases:["menstrual"], keyNutrient:"Fast carbs · Easy digestion", phaseReasons:{menstrual:"Easy to digest comfort food when appetite is low during period"} },
  { id:"pasta", name:"Pasta (cooked)", emoji:"🍝", category:"grain", per100g:{calories:158,protein:5.8,carbs:31,fats:0.9,fiber:1.8}, phases:["luteal","ovulation"], keyNutrient:"Complex carbs · B vitamins · Iron", phaseReasons:{luteal:"Carbs boost serotonin production, directly improving PMS mood",ovulation:"Sustained energy source for peak performance days"} },
  { id:"bread_whole", name:"Wholegrain Bread", emoji:"🍞", category:"grain", per100g:{calories:247,protein:13,carbs:41,fats:3.4,fiber:6.0}, phases:["luteal","follicular"], keyNutrient:"Fibre · B vitamins · Iron", phaseReasons:{luteal:"High fibre reduces bloating; B vitamins support mood regulation",follicular:"Sustained energy from complex carbs supports building strength"} },
  { id:"bread_white", name:"White Bread", emoji:"🍞", category:"grain", per100g:{calories:265,protein:9.0,carbs:49,fats:3.2,fiber:2.3}, phases:["menstrual"], keyNutrient:"Fast carbs · Comfort energy", phaseReasons:{menstrual:"Easy digestible comfort food when energy is low and appetite is off"} },
  { id:"quinoa", name:"Quinoa (cooked)", emoji:"🌾", category:"grain", per100g:{calories:120,protein:4.4,carbs:22,fats:1.9,fiber:2.8}, phases:["follicular","ovulation"], keyNutrient:"Complete protein · Iron · Magnesium", phaseReasons:{follicular:"Complete protein with all amino acids supports muscle and hormone building",ovulation:"Iron and magnesium support peak energy and physical performance"} },
  { id:"lentils", name:"Lentils (cooked)", emoji:"🫘", category:"grain", per100g:{calories:116,protein:9.0,carbs:20,fats:0.4,fiber:7.9}, phases:["menstrual","follicular"], keyNutrient:"Iron · Folate · Fibre", phaseReasons:{menstrual:"High iron replaces blood loss; folate supports cell regeneration",follicular:"Folate essential for healthy egg development; fibre clears excess hormones"} },
  { id:"chickpeas", name:"Chickpeas", emoji:"🫘", category:"grain", per100g:{calories:164,protein:8.9,carbs:27,fats:2.6,fiber:7.6}, phases:["follicular","luteal"], keyNutrient:"Folate · Iron · Phytoestrogens", phaseReasons:{follicular:"Phytoestrogens support oestrogen balance; folate aids egg health",luteal:"High fibre reduces bloating; iron supports energy before period"} },
  { id:"black_beans", name:"Black Beans", emoji:"🫘", category:"grain", per100g:{calories:132,protein:8.9,carbs:24,fats:0.5,fiber:8.7}, phases:["menstrual","luteal"], keyNutrient:"Iron · Magnesium · Fibre", phaseReasons:{menstrual:"Iron replenishes blood loss; magnesium reduces cramping severity",luteal:"Fibre reduces bloating; magnesium calms PMS mood and sleep issues"} },
  { id:"sourdough", name:"Sourdough", emoji:"🍞", category:"grain", per100g:{calories:267,protein:9.0,carbs:51,fats:1.2,fiber:2.0}, phases:["follicular","luteal"], keyNutrient:"Prebiotic fibre · Lower GI · B vitamins", phaseReasons:{follicular:"Fermentation improves gut health which supports oestrogen metabolism",luteal:"Lower glycaemic than regular bread; prebiotics reduce PMS bloating"} },

  // DAIRY
  { id:"greek_yogurt", name:"Greek Yogurt", emoji:"🫙", category:"dairy", per100g:{calories:59,protein:10,carbs:3.6,fats:0.4}, phases:["menstrual","luteal"], keyNutrient:"Calcium · Probiotics · Protein", phaseReasons:{menstrual:"Calcium reduces muscle cramping; probiotics ease digestive discomfort",luteal:"Calcium reduces PMS severity; tryptophan supports serotonin production"} },
  { id:"milk_whole", name:"Whole Milk", emoji:"🥛", category:"dairy", per100g:{calories:61,protein:3.2,carbs:4.8,fats:3.3}, phases:["menstrual","luteal"], keyNutrient:"Calcium · Vitamin D · Iodine", phaseReasons:{menstrual:"Calcium reduces cramp severity; Vitamin D supports immune function",luteal:"Calcium directly reduces PMS symptoms including mood changes"} },
  { id:"milk_skim", name:"Skim Milk", emoji:"🥛", category:"dairy", per100g:{calories:35,protein:3.4,carbs:5.0,fats:0.1}, phases:["menstrual","follicular"], keyNutrient:"Calcium · Protein · Iodine", phaseReasons:{menstrual:"Calcium reduces cramping with minimal calories during low-appetite phase",follicular:"Iodine supports thyroid function which regulates the menstrual cycle"} },
  { id:"cheese_cheddar", name:"Cheddar Cheese", emoji:"🧀", category:"dairy", per100g:{calories:402,protein:25,carbs:1.3,fats:33}, phases:["menstrual","luteal"], keyNutrient:"Calcium · Vitamin K2 · Protein", phaseReasons:{menstrual:"Calcium eases cramps; satisfies comfort cravings during period",luteal:"Calcium reduces PMS symptoms; tryptophan supports serotonin"} },
  { id:"cheese_feta", name:"Feta Cheese", emoji:"🧀", category:"dairy", per100g:{calories:264,protein:14,carbs:4.1,fats:21}, phases:["follicular","ovulation"], keyNutrient:"Calcium · Probiotics · Vitamin B12", phaseReasons:{follicular:"B12 supports energy and red blood cell production during rebuilding",ovulation:"Calcium and protein support peak physical performance"} },
  { id:"cottage_cheese", name:"Cottage Cheese", emoji:"🫙", category:"dairy", per100g:{calories:98,protein:11,carbs:3.4,fats:4.3}, phases:["follicular","ovulation"], keyNutrient:"Casein protein · Selenium · B12", phaseReasons:{follicular:"Slow-releasing casein protein supports muscle building",ovulation:"Selenium supports egg quality; high protein aids peak performance"} },
  { id:"kefir", name:"Kefir", emoji:"🥛", category:"dairy", per100g:{calories:61,protein:3.3,carbs:4.5,fats:3.3}, phases:["luteal","menstrual"], keyNutrient:"Probiotics · Calcium · B vitamins", phaseReasons:{luteal:"Probiotics reduce PMS bloating; calcium reduces mood symptoms",menstrual:"Beneficial bacteria ease digestive discomfort during period"} },
  { id:"butter", name:"Butter", emoji:"🧈", category:"dairy", per100g:{calories:717,protein:0.9,carbs:0.1,fats:81}, phases:["follicular","luteal"], keyNutrient:"Vitamin A · Butyrate · Fat-soluble vitamins", phaseReasons:{follicular:"Vitamin A supports hormone synthesis and reproductive health",luteal:"Butyrate feeds gut bacteria which helps regulate oestrogen levels"} },

  // FATS & NUTS
  { id:"almonds", name:"Almonds", emoji:"🌰", category:"fat", per100g:{calories:579,protein:21,carbs:22,fats:50,fiber:12.5}, phases:["menstrual","luteal"], keyNutrient:"Magnesium · Vitamin E · Healthy fats", phaseReasons:{menstrual:"Magnesium reduces cramps; Vitamin E reduces PMS breast tenderness",luteal:"Magnesium calms PMS anxiety; Vitamin E reduces premenstrual symptoms"} },
  { id:"walnuts", name:"Walnuts", emoji:"🌰", category:"fat", per100g:{calories:654,protein:15,carbs:14,fats:65,fiber:6.7}, phases:["menstrual","follicular","luteal"], keyNutrient:"ALA Omega-3 · Melatonin · Magnesium", phaseReasons:{menstrual:"Plant omega-3 reduces inflammation and menstrual pain",follicular:"Supports healthy hormone production and brain function",luteal:"Melatonin improves sleep; magnesium reduces PMS symptoms"} },
  { id:"cashews", name:"Cashews", emoji:"🌰", category:"fat", per100g:{calories:553,protein:18,carbs:30,fats:44,fiber:3.3}, phases:["menstrual","follicular"], keyNutrient:"Iron · Zinc · Magnesium", phaseReasons:{menstrual:"Iron replenishes blood loss; zinc supports immune function during period",follicular:"Zinc supports follicle development and healthy egg maturation"} },
  { id:"peanuts", name:"Peanuts", emoji:"🥜", category:"fat", per100g:{calories:567,protein:26,carbs:16,fats:49,fiber:8.5}, phases:["follicular","ovulation"], keyNutrient:"Folate · Niacin · Resveratrol", phaseReasons:{follicular:"Folate supports egg development and DNA synthesis",ovulation:"Niacin supports energy metabolism at peak performance"} },
  { id:"pumpkin_seeds", name:"Pumpkin Seeds", emoji:"🎃", category:"fat", per100g:{calories:559,protein:30,carbs:11,fats:49,fiber:6.0}, phases:["menstrual","follicular"], keyNutrient:"Zinc · Iron · Magnesium", phaseReasons:{menstrual:"Zinc supports immune function; iron replenishes period blood loss",follicular:"Zinc is critical for healthy follicle development and ovulation"} },
  { id:"sunflower_seeds", name:"Sunflower Seeds", emoji:"🌻", category:"fat", per100g:{calories:584,protein:21,carbs:20,fats:51,fiber:8.6}, phases:["luteal","follicular"], keyNutrient:"Vitamin E · Selenium · Magnesium", phaseReasons:{luteal:"Vitamin E reduces PMS breast tenderness; selenium supports thyroid",follicular:"Selenium supports healthy hormone production and egg quality"} },
  { id:"olive_oil", name:"Olive Oil", emoji:"🫙", category:"fat", per100g:{calories:884,protein:0,carbs:0,fats:100}, phases:["menstrual","follicular","luteal"], keyNutrient:"Oleocanthal · Vitamin E · Polyphenols", phaseReasons:{menstrual:"Oleocanthal is a natural anti-inflammatory that reduces period cramps",follicular:"Healthy monounsaturated fats support hormone production",luteal:"Polyphenols reduce oxidative stress and PMS inflammation"} },
  { id:"dark_chocolate", name:"Dark Chocolate", emoji:"🍫", category:"fat", per100g:{calories:598,protein:8.0,carbs:46,fats:43,fiber:10.9}, phases:["menstrual","luteal"], keyNutrient:"Magnesium · Iron · Theobromine", phaseReasons:{menstrual:"Magnesium reduces cramps; iron replenishes blood loss; natural mood booster",luteal:"Satisfies chocolate cravings while providing magnesium for PMS relief"} },
  { id:"peanut_butter", name:"Peanut Butter", emoji:"🥜", category:"fat", per100g:{calories:588,protein:25,carbs:20,fats:50,fiber:6.0}, phases:["luteal","follicular"], keyNutrient:"Tryptophan · Magnesium · Niacin", phaseReasons:{luteal:"Tryptophan boosts serotonin; satisfies PMS comfort cravings healthily",follicular:"High protein and healthy fats support hormone synthesis"} },
  { id:"chia_seeds", name:"Chia Seeds", emoji:"🌿", category:"fat", per100g:{calories:486,protein:17,carbs:42,fats:31,fiber:34.4}, phases:["menstrual","luteal"], keyNutrient:"Omega-3 · Calcium · Fibre", phaseReasons:{menstrual:"Omega-3 reduces inflammation; calcium eases cramps; fibre supports digestion",luteal:"Reduces bloating; omega-3 supports mood regulation before period"} },
  { id:"flaxseeds", name:"Flaxseeds", emoji:"🌻", category:"fat", per100g:{calories:534,protein:18,carbs:29,fats:42,fiber:27.3}, phases:["follicular","ovulation"], keyNutrient:"Lignans · Omega-3 · Fibre", phaseReasons:{follicular:"Lignans support healthy oestrogen balance during the building phase",ovulation:"Supports oestrogen peak and promotes healthy ovulation"} },

  // OTHER
  { id:"honey", name:"Honey", emoji:"🍯", category:"other", per100g:{calories:304,protein:0.3,carbs:82,fats:0}, phases:["menstrual","luteal"], keyNutrient:"Prostaglandin inhibitors · Antioxidants · Enzymes", phaseReasons:{menstrual:"Natural compounds help inhibit prostaglandins that cause cramp pain",luteal:"Satisfies sweet cravings naturally; antioxidants reduce inflammation"} },
  { id:"hummus", name:"Hummus", emoji:"🫙", category:"other", per100g:{calories:166,protein:8.0,carbs:14,fats:10}, phases:["follicular","luteal"], keyNutrient:"Iron · Folate · Healthy fats", phaseReasons:{follicular:"Folate from chickpeas supports egg development; iron boosts energy",luteal:"Fibre reduces bloating; healthy fats support hormone balance"} },
  { id:"protein_shake", name:"Protein Shake", emoji:"🥤", category:"protein", per100g:{calories:400,protein:80,carbs:5.0,fats:5.0}, phases:["follicular","ovulation"], keyNutrient:"Whey protein · BCAAs · Leucine", phaseReasons:{follicular:"High protein supports muscle building as strength and energy return",ovulation:"Supports peak performance recovery and muscle protein synthesis"} },
  { id:"granola", name:"Granola", emoji:"🌾", category:"grain", per100g:{calories:471,protein:10,carbs:64,fats:20,fiber:5.0}, phases:["follicular","luteal"], keyNutrient:"Oat beta-glucan · Iron · Magnesium", phaseReasons:{follicular:"Sustained energy from oats supports building strength in early cycle",luteal:"Magnesium from oats reduces PMS mood symptoms and sweet cravings"} },
  { id:"banana_bread", name:"Banana Bread", emoji:"🍌", category:"grain", per100g:{calories:326,protein:5.0,carbs:55,fats:10}, phases:["menstrual","luteal"], keyNutrient:"B6 · Magnesium · Comfort carbs", phaseReasons:{menstrual:"Comfort food with B6 and magnesium from bananas to ease cramps",luteal:"Satisfies carb and sweet cravings; B6 supports serotonin production"} },

  // PROTEINS — new
  { id:"beef_mince", name:"Beef Mince (lean)", emoji:"🥩", category:"protein", per100g:{calories:215,protein:26,carbs:0,fats:12}, phases:["menstrual","follicular"], keyNutrient:"Iron · Zinc · B12", phaseReasons:{menstrual:"Haem iron replenishes blood loss; zinc reduces inflammation",follicular:"Zinc supports ovarian function; B12 boosts energy as hormones rise"} },
  { id:"chicken_thigh", name:"Chicken Thigh", emoji:"🍗", category:"protein", per100g:{calories:209,protein:26,carbs:0,fats:12}, phases:["follicular","ovulation"], keyNutrient:"Protein · Zinc · B6", phaseReasons:{follicular:"Complete protein supports muscle building as oestrogen rises",ovulation:"Zinc and B6 support peak hormonal activity and energy"} },
  { id:"turkey_breast", name:"Turkey Breast", emoji:"🦃", category:"protein", per100g:{calories:135,protein:30,carbs:0,fats:1.0}, phases:["follicular","ovulation"], keyNutrient:"Tryptophan · Selenium · B3", phaseReasons:{follicular:"Tryptophan boosts serotonin; selenium supports thyroid",ovulation:"Lean protein for peak performance; selenium protects egg quality"} },
  { id:"shrimp", name:"Shrimp / Prawns", emoji:"🍤", category:"protein", per100g:{calories:99,protein:24,carbs:0.2,fats:0.3}, phases:["follicular","ovulation"], keyNutrient:"Iodine · Selenium · Zinc", phaseReasons:{follicular:"Iodine supports thyroid and oestrogen balance",ovulation:"Selenium and zinc support peak fertility window"} },
  { id:"tuna_canned", name:"Tuna (canned)", emoji:"🐟", category:"protein", per100g:{calories:116,protein:26,carbs:0,fats:1.0}, phases:["menstrual","follicular"], keyNutrient:"Omega-3 · Selenium · B12", phaseReasons:{menstrual:"Omega-3 reduces inflammation and cramping",follicular:"Selenium supports thyroid and egg development"} },
  { id:"tempeh", name:"Tempeh", emoji:"🟫", category:"protein", per100g:{calories:193,protein:19,carbs:9.0,fats:11,fiber:4.0}, phases:["follicular","luteal"], keyNutrient:"Phytoestrogens · Iron · Probiotics", phaseReasons:{follicular:"Phytoestrogens gently support oestrogen levels as cycle rebuilds",luteal:"Probiotics support gut health; iron maintains energy"} },
  { id:"edamame", name:"Edamame", emoji:"🫘", category:"protein", per100g:{calories:121,protein:11,carbs:9.0,fats:5.2,fiber:5.2}, phases:["follicular","ovulation"], keyNutrient:"Folate · Isoflavones · Vitamin K", phaseReasons:{follicular:"Folate supports egg development; isoflavones support oestrogen",ovulation:"Vitamin K and folate support fertility at peak window"} },
  { id:"sardines", name:"Sardines", emoji:"🐠", category:"protein", per100g:{calories:208,protein:25,carbs:0,fats:11}, phases:["menstrual","luteal"], keyNutrient:"Omega-3 · Calcium · Vitamin D", phaseReasons:{menstrual:"Omega-3 reduces cramps; calcium supports muscle function",luteal:"Vitamin D supports mood; calcium reduces PMS symptoms"} },

  // GRAINS — new
  { id:"buckwheat", name:"Buckwheat", emoji:"🌾", category:"grain", per100g:{calories:343,protein:13,carbs:72,fats:3.4,fiber:10}, phases:["follicular","menstrual"], keyNutrient:"Rutin · Magnesium · Complete protein", phaseReasons:{follicular:"Rutin strengthens blood vessels; magnesium supports hormone production",menstrual:"Magnesium eases cramps; plant protein replenishes energy"} },
  { id:"millet", name:"Millet", emoji:"🟡", category:"grain", per100g:{calories:378,protein:11,carbs:73,fats:4.2,fiber:8.5}, phases:["menstrual","luteal"], keyNutrient:"Magnesium · Iron · Antioxidants", phaseReasons:{menstrual:"Iron and magnesium replenish what's lost during bleeding",luteal:"Magnesium reduces PMS; slow-release energy stabilises mood"} },
  { id:"sourdough", name:"Sourdough Bread", emoji:"🍞", category:"grain", per100g:{calories:274,protein:9.0,carbs:53,fats:1.4,fiber:2.4}, phases:["follicular","ovulation"], keyNutrient:"B vitamins · Fermented · Lower GI", phaseReasons:{follicular:"Fermentation increases B vitamin bioavailability; lower GI than regular bread",ovulation:"Steady energy for peak performance; easier digestion"} },
  { id:"rye_bread", name:"Rye Bread", emoji:"🍞", category:"grain", per100g:{calories:259,protein:8.5,carbs:48,fats:3.3,fiber:6.0}, phases:["luteal","menstrual"], keyNutrient:"Fibre · Lignans · B vitamins", phaseReasons:{luteal:"Lignans support oestrogen clearance; fibre reduces bloating",menstrual:"Slow-release carbs maintain steady energy during low phase"} },
  { id:"pasta_wholemeal", name:"Wholemeal Pasta", emoji:"🍝", category:"grain", per100g:{calories:352,protein:13,carbs:67,fats:2.5,fiber:8.0}, phases:["follicular","ovulation"], keyNutrient:"Complex carbs · B vitamins · Iron", phaseReasons:{follicular:"Sustained energy for building strength; iron supports energy levels",ovulation:"High carb fuel for peak performance and intense training"} },

  // DAIRY — new
  { id:"ricotta", name:"Ricotta", emoji:"🧀", category:"dairy", per100g:{calories:174,protein:11,carbs:3.0,fats:13}, phases:["follicular","ovulation"], keyNutrient:"Calcium · Whey protein · B12", phaseReasons:{follicular:"Easily digestible protein for muscle repair; calcium for bone health",ovulation:"Light protein source; B12 supports peak energy"} },
  { id:"halloumi", name:"Halloumi", emoji:"🧀", category:"dairy", per100g:{calories:321,protein:22,carbs:1.0,fats:25}, phases:["follicular","ovulation"], keyNutrient:"Calcium · Protein · Sodium", phaseReasons:{follicular:"High protein for muscle building; calcium supports bone density",ovulation:"Satisfying protein for peak phase energy demands"} },
  { id:"skyr", name:"Skyr (Icelandic Yogurt)", emoji:"🥛", category:"dairy", per100g:{calories:63,protein:11,carbs:4.0,fats:0.2}, phases:["follicular","ovulation"], keyNutrient:"Protein · Calcium · Probiotics", phaseReasons:{follicular:"Higher protein than regular yogurt; probiotics support gut-hormone axis",ovulation:"Light, high-protein; ideal pre or post training"} },
  { id:"butter", name:"Butter", emoji:"🧈", category:"fat", per100g:{calories:717,protein:0.9,carbs:0.1,fats:81}, phases:["menstrual","luteal"], keyNutrient:"Fat-soluble vitamins · CLA · Butyrate", phaseReasons:{menstrual:"Butyrate supports gut lining health during hormonal changes",luteal:"Saturated fat supports hormone production; small amounts are fine"} },

  // FATS — new
  { id:"tahini", name:"Tahini", emoji:"🫙", category:"fat", per100g:{calories:595,protein:17,carbs:21,fats:54,fiber:9.3}, phases:["menstrual","follicular"], keyNutrient:"Calcium · Iron · Sesamin", phaseReasons:{menstrual:"Sesamin supports oestrogen metabolism; calcium reduces cramping",follicular:"Iron boosts energy; calcium supports bone health"} },
  { id:"coconut_oil", name:"Coconut Oil", emoji:"🥥", category:"fat", per100g:{calories:862,protein:0,carbs:0,fats:100}, phases:["menstrual","luteal"], keyNutrient:"MCTs · Lauric acid", phaseReasons:{menstrual:"MCTs provide quick energy without spiking blood sugar during low phase",luteal:"Lauric acid has anti-inflammatory properties; supports immune function"} },
  { id:"pumpkin_seeds", name:"Pumpkin Seeds", emoji:"🎃", category:"fat", per100g:{calories:559,protein:30,carbs:11,fats:49,fiber:6.0}, phases:["follicular","ovulation"], keyNutrient:"Zinc · Magnesium · Phytosterols", phaseReasons:{follicular:"Zinc triggers LH surge and ovulation; magnesium supports follicle growth",ovulation:"Zinc supports the dominant follicle and egg quality at peak"} },
  { id:"sunflower_seeds", name:"Sunflower Seeds", emoji:"🌻", category:"fat", per100g:{calories:584,protein:21,carbs:20,fats:51,fiber:8.6}, phases:["luteal","ovulation"], keyNutrient:"Vitamin E · Selenium · Linoleic acid", phaseReasons:{luteal:"Vitamin E supports progesterone production in luteal phase",ovulation:"Selenium protects egg from oxidative stress at peak fertility"} },
  { id:"sesame_seeds", name:"Sesame Seeds", emoji:"⚪", category:"fat", per100g:{calories:573,protein:18,carbs:23,fats:50,fiber:12}, phases:["menstrual","follicular"], keyNutrient:"Calcium · Lignans · Iron", phaseReasons:{menstrual:"Calcium reduces cramps; iron replenishes blood loss",follicular:"Lignans support oestrogen metabolism as cycle rebuilds"} },

  // DRINKS — new
  { id:"matcha", name:"Matcha", emoji:"🍵", category:"drink", per100g:{calories:324,protein:30,carbs:39,fats:5.0}, phases:["follicular","ovulation"], keyNutrient:"L-theanine · EGCG · Caffeine", phaseReasons:{follicular:"L-theanine + caffeine = calm focus; EGCG is strongly anti-inflammatory",ovulation:"Supports peak energy without cortisol spike from coffee"} },
  { id:"bone_broth", name:"Bone Broth", emoji:"🍲", category:"drink", per100g:{calories:25,protein:5.0,carbs:0,fats:0.5}, phases:["menstrual","luteal"], keyNutrient:"Collagen · Glycine · Minerals", phaseReasons:{menstrual:"Glycine is anti-inflammatory; collagen supports joint comfort during cramps",luteal:"Gut-healing; mineral-rich; warm and comforting before period"} },
  { id:"golden_milk", name:"Golden Milk (Turmeric Latte)", emoji:"🥛", category:"drink", per100g:{calories:60,protein:3.0,carbs:7.0,fats:2.5}, phases:["menstrual","luteal"], keyNutrient:"Curcumin · Ginger · Black pepper", phaseReasons:{menstrual:"Curcumin is one of the most potent natural anti-inflammatory compounds",luteal:"Reduces PMS inflammation; warming and calming before sleep"} },
  { id:"coconut_water", name:"Coconut Water", emoji:"🥥", category:"drink", per100g:{calories:19,protein:0.7,carbs:3.7,fats:0.2}, phases:["menstrual","ovulation"], keyNutrient:"Electrolytes · Potassium · Cytokinins", phaseReasons:{menstrual:"Natural electrolytes reduce cramping and bloating; better than sports drinks",ovulation:"Hydration for peak performance; potassium supports muscle function"} },
  { id:"green_juice", name:"Green Juice", emoji:"🥤", category:"drink", per100g:{calories:40,protein:2.0,carbs:8.0,fats:0.3}, phases:["follicular","ovulation"], keyNutrient:"Chlorophyll · Vitamin C · Folate", phaseReasons:{follicular:"Chlorophyll supports detox; folate is key for egg development",ovulation:"Vitamin C and antioxidants protect egg quality at peak"} },

  // OTHER / CONDIMENTS
  { id:"miso", name:"Miso Paste", emoji:"🍜", category:"other", per100g:{calories:199,protein:12,carbs:26,fats:6.0}, phases:["follicular","luteal"], keyNutrient:"Probiotics · Isoflavones · B vitamins", phaseReasons:{follicular:"Probiotics support gut-hormone axis; isoflavones modulate oestrogen",luteal:"Gut health reduces PMS symptoms; B vitamins support mood"} },
  { id:"nutritional_yeast", name:"Nutritional Yeast", emoji:"🟡", category:"other", per100g:{calories:325,protein:50,carbs:38,fats:5.0,fiber:7.0}, phases:["menstrual","follicular"], keyNutrient:"B12 · Folate · Complete protein", phaseReasons:{menstrual:"B12 supports energy during blood loss; folate replenishes",follicular:"All B vitamins in one; supports hormone production and energy"} },
  { id:"soy_sauce", name:"Soy Sauce (low sodium)", emoji:"🍶", category:"other", per100g:{calories:60,protein:10,carbs:6.0,fats:0.1}, phases:["follicular","luteal"], keyNutrient:"Isoflavones · Glutamate · Minerals", phaseReasons:{follicular:"Isoflavones support healthy oestrogen activity",luteal:"Umami satisfaction reduces cravings; low calorie flavour boost"} },
  { id:"apple_cider_vinegar", name:"Apple Cider Vinegar", emoji:"🍎", category:"other", per100g:{calories:22,protein:0,carbs:0.9,fats:0}, phases:["follicular","luteal"], keyNutrient:"Acetic acid · Probiotics · Enzymes", phaseReasons:{follicular:"Supports blood sugar balance as metabolism increases",luteal:"Reduces insulin spikes that worsen PMS cravings and bloating"} },
];

export function searchQuickFoods(query: string): QuickFood[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return QUICK_FOODS.filter(f =>
    f.name.toLowerCase().includes(q) ||
    f.category.includes(q) ||
    f.keyNutrient.toLowerCase().includes(q)
  ).slice(0, 8);
}
