// scripts/transformRecipes.ts
// Transforms the 120 package recipes to the new HerPhase recipe schema.
// Usage: npx ts-node --skip-project --compiler-options '{"module":"commonjs"}' scripts/transformRecipes.ts > /tmp/seed_recipes.sql
// Then run the output SQL in the Supabase SQL editor.

// eslint-disable-next-line @typescript-eslint/no-require-imports
const rawRecipes = require("../../meal_app_package/meal_app_package/recipes.json") as OldRecipe[];

interface OldRecipe {
  id: number;
  slug: string;
  name: string;
  phase: string;
  prep_time_min: number;
  difficulty: string;
  macro_type: string;
  goals: string[];
  tags: string[];
  ingredients: string[];
  estimated_macros: {
    calories_kcal: number;
    protein_g: number;
    carbs_g: number;
    fat_g: number;
  };
  servings: number;
  instructions: string[];
  app_flags: { female_fitness: boolean; fast_recipe: boolean; phase_recommended: boolean };
}

// Tags that map to symptom signals
const SYMPTOM_TAGS = new Set([
  "anti_inflammatory", "cramp_support", "recovery", "iron_support",
  "comfort", "magnesium_support", "mood_support", "craving_control",
  "anti_bloat", "bloat_friendly",
]);

// Tags that map to energy level signals
const ENERGY_TAGS = new Set([
  "steady_energy", "high_energy", "low_energy", "energy",
  "quick_energy", "balanced_fuel", "light_fuel",
]);

const MEATS = ["beef", "chicken", "turkey", "pork", "lamb", "bacon"];
const FISH  = ["salmon", "tuna", "shrimp", "cod", "mackerel", "fish"];
const BREAKFAST_WORDS = ["egg", "oat", "smoothie", "yogurt", "pancake", "granola", "porridge"];
const SNACK_CAL_LIMIT = 300;
const SNACK_PREP_LIMIT = 10;

function inferMealTypes(recipe: OldRecipe): string[] {
  const nameLower = recipe.name.toLowerCase();
  const types: Set<string> = new Set();

  // Breakfast: name contains breakfast-associated words
  if (BREAKFAST_WORDS.some(w => nameLower.includes(w))) {
    types.add("breakfast");
  }

  // Snack: very quick AND low calorie
  if (
    recipe.prep_time_min <= SNACK_PREP_LIMIT &&
    recipe.estimated_macros.calories_kcal < SNACK_CAL_LIMIT
  ) {
    types.add("snack");
  }

  // Lunch + dinner: everything except pure snacks
  const isSnackOnly = types.size === 1 && types.has("snack");
  if (!isSnackOnly) {
    types.add("lunch");
    types.add("dinner");
  }

  // Default fallback
  if (types.size === 0) {
    types.add("lunch");
    types.add("dinner");
  }

  return Array.from(types);
}

function classify(tags: string[]) {
  const phaseTags:   string[] = [];
  const symptomTags: string[] = [];
  const energyTags:  string[] = [];

  for (const tag of tags) {
    if (ENERGY_TAGS.has(tag))        energyTags.push(tag);
    else if (SYMPTOM_TAGS.has(tag))  symptomTags.push(tag);
    else                             phaseTags.push(tag);
  }
  return { phaseTags, symptomTags, energyTags };
}

function hasIngredient(ingredients: string[], list: string[]): boolean {
  return ingredients.some(ing => list.some(w => ing.toLowerCase().includes(w)));
}

function escapeSql(s: string): string {
  return s.replace(/'/g, "''");
}

function pgArray(arr: string[]): string {
  return `ARRAY[${arr.map(s => `'${escapeSql(s)}'`).join(",")}]`;
}

function pgBool(b: boolean): string {
  return b ? "true" : "false";
}

const rows: string[] = rawRecipes.map((r) => {
  const { phaseTags, symptomTags, energyTags } = classify(r.tags);
  const mealTypes = inferMealTypes(r);

  const hasMeat      = hasIngredient(r.ingredients, MEATS);
  const hasFish      = hasIngredient(r.ingredients, FISH);
  const isVegetarian = !hasMeat && !hasFish;
  const isPescatarian = !hasMeat && hasFish;
  const isHighProtein = r.macro_type === "high_protein";
  const isComfort    = r.tags.includes("comfort") || r.tags.includes("warm");
  const isLowBloat   = r.tags.includes("anti_bloat") || r.tags.includes("fresh") || r.tags.includes("light");

  return `(
  '${escapeSql(r.slug)}',
  '${escapeSql(r.name)}',
  ARRAY['${r.phase}'],
  ${pgArray(mealTypes)},
  ${r.prep_time_min},
  0,
  '${r.difficulty}',
  '${r.macro_type === "high_protein" ? "high_protein" : r.macro_type === "carb_focus" ? "carb_focus" : r.macro_type === "fat_focus" ? "fat_focus" : "balanced"}',
  ${pgArray(r.goals)},
  ${pgArray(phaseTags)},
  ${pgArray(symptomTags)},
  ${pgArray(energyTags)},
  ${r.estimated_macros.calories_kcal},
  ${r.estimated_macros.protein_g},
  ${r.estimated_macros.carbs_g},
  ${r.estimated_macros.fat_g},
  0,
  ${pgArray(r.ingredients)},
  ${pgArray(r.instructions)},
  false,
  ${pgBool(isVegetarian)},
  ${pgBool(isPescatarian)},
  ${pgBool(isHighProtein)},
  ${pgBool(isComfort)},
  ${pgBool(isLowBloat)},
  0,
  null,
  ''
)`;
});

const sql = `
-- Seed: 120 HerPhase recipes (transformed from meal_app_package)
-- Generated by scripts/transformRecipes.ts

insert into public.recipes (
  slug, name, phases, meal_types,
  prep_time_min, cook_time_min,
  difficulty, macro_profile,
  goals, phase_tags, symptom_tags, energy_tags,
  calories, protein_g, carbs_g, fat_g, fiber_g,
  ingredients, instructions,
  has_real_instructions,
  is_vegetarian, is_pescatarian, is_high_protein,
  is_comfort_meal, is_low_bloat,
  sort_priority, image_url, benefits
) values
${rows.join(",\n")}
on conflict (slug) do nothing;
`;

process.stdout.write(sql);
